using SkyVault.WebApi.Backend.Models;

namespace SkyVault.WebApi.Backend.Seeds
{
    public class CountrySeedData
    {
        private static int idCounter = 1;

        public static readonly List<Country> countries = new List<Country>
        {
            new Country { Id=idCounter++, CountryCode="AFG", CountryName = "Afghanistan" },
            new Country { Id=idCounter++, CountryCode="ALA", CountryName = "Albania" },
            new Country { Id=idCounter++, CountryCode="ALB", CountryName = "Algeria" },
            new Country { Id=idCounter++, CountryCode="AND", CountryName = "Andorra" },
            new Country { Id=idCounter++, CountryCode="AGO", CountryName = "Angola" },
            new Country { Id=idCounter++, CountryCode="AIA", CountryName = "Anguilla" },
            new Country { Id=idCounter++, CountryCode="ATA", CountryName = "Antarctica" },
            new Country { Id=idCounter++, CountryCode="ATG", CountryName = "Antigua and Barbuda" },
            new Country { Id=idCounter++, CountryCode="ARG", CountryName = "Argentina" },
            new Country { Id=idCounter++, CountryCode="ARM", CountryName = "Armenia" },
            new Country { Id=idCounter++, CountryCode="ABW", CountryName = "Aruba" },
            new Country { Id=idCounter++, CountryCode="AUS", CountryName = "Australia" },
            new Country { Id=idCounter++, CountryCode="AUT", CountryName = "Austria" },
            new Country { Id=idCounter++, CountryCode="AZE", CountryName = "Azerbaijan" },
            new Country { Id=idCounter++, CountryCode="BHS", CountryName = "Bahamas" },
            new Country { Id=idCounter++, CountryCode="BHR", CountryName = "Bahrain" },
            new Country { Id=idCounter++, CountryCode="BGD", CountryName = "Bangladesh" },
            new Country { Id=idCounter++, CountryCode="BRB", CountryName = "Barbados" },
            new Country { Id=idCounter++, CountryCode="BLR", CountryName = "Belarus" },
            new Country { Id=idCounter++, CountryCode="BEL", CountryName = "Belgium" },
            new Country { Id=idCounter++, CountryCode="BLZ", CountryName = "Belize" },
            new Country { Id=idCounter++, CountryCode="BEN", CountryName = "Benin" },
            new Country { Id=idCounter++, CountryCode="BMU", CountryName = "Bermuda" },
            new Country { Id=idCounter++, CountryCode="BTN", CountryName = "Bhutan" },
            new Country { Id=idCounter++, CountryCode="BOL", CountryName = "Bolivia" },
            new Country { Id=idCounter++, CountryCode="BES", CountryName = "Bonaire, Sint Eustatius and Saba" },
            new Country { Id=idCounter++, CountryCode="BIH", CountryName = "Bosnia and Herzegovina" },
            new Country { Id=idCounter++, CountryCode="BWA", CountryName = "Botswana" },
            new Country { Id=idCounter++, CountryCode="BVT", CountryName = "Bouvet Island" },
            new Country { Id=idCounter++, CountryCode="BRA", CountryName = "Brazil" },
            new Country { Id=idCounter++, CountryCode="IOT", CountryName = "British Indian Ocean Territory" },
            new Country { Id=idCounter++, CountryCode="BRN", CountryName = "Brunei Darussalam" },
            new Country { Id=idCounter++, CountryCode="BGR", CountryName = "Bulgaria" },
            new Country { Id=idCounter++, CountryCode="BFA", CountryName = "Burkina Faso" },
            new Country { Id=idCounter++, CountryCode="BDI", CountryName = "Burundi" },
            new Country { Id=idCounter++, CountryCode="CPV", CountryName = "Cabo Verde" },
            new Country { Id=idCounter++, CountryCode="KHM", CountryName = "Cambodia" },
            new Country { Id=idCounter++, CountryCode="CMR", CountryName = "Cameroon" },
            new Country { Id=idCounter++, CountryCode="CAN", CountryName = "Canada" },
            new Country { Id=idCounter++, CountryCode="CYM", CountryName = "Cayman Islands" },
            new Country { Id=idCounter++, CountryCode="CAF", CountryName = "Central African Republic" },
            new Country { Id=idCounter++, CountryCode="TCD", CountryName = "Chad" },
            new Country { Id=idCounter++, CountryCode="CHL", CountryName = "Chile" },
            new Country { Id=idCounter++, CountryCode="CHN", CountryName = "China" },
            new Country { Id=idCounter++, CountryCode="CXR", CountryName = "Christmas Island" },
            new Country { Id=idCounter++, CountryCode="CCK", CountryName = "Cocos (Keeling) Islands" },
            new Country { Id=idCounter++, CountryCode="COL", CountryName = "Colombia" },
            new Country { Id=idCounter++, CountryCode="COM", CountryName = "Comoros" },
            new Country { Id=idCounter++, CountryCode="COG", CountryName = "Congo" },
            new Country { Id=idCounter++, CountryCode="COD", CountryName = "Congo, Democratic Republic of the" },
            new Country { Id=idCounter++, CountryCode="COK", CountryName = "Cook Islands" },
            new Country { Id=idCounter++, CountryCode="CRI", CountryName = "Costa Rica" },
            new Country { Id=idCounter++, CountryCode="HRV", CountryName = "Croatia" },
            new Country { Id=idCounter++, CountryCode="CUB", CountryName = "Cuba" },
            new Country { Id=idCounter++, CountryCode="CUW", CountryName = "Curaçao" },
            new Country { Id=idCounter++, CountryCode="CYP", CountryName = "Cyprus" },
            new Country { Id=idCounter++, CountryCode="CZE", CountryName = "Czech Republic" },
            new Country { Id=idCounter++, CountryCode="DNK", CountryName = "Denmark" },
            new Country { Id=idCounter++, CountryCode="DJI", CountryName = "Djibouti" },
            new Country { Id=idCounter++, CountryCode="DMA", CountryName = "Dominica" },
            new Country { Id=idCounter++, CountryCode="DOM", CountryName = "Dominican Republic" },
            new Country { Id=idCounter++, CountryCode="ECU", CountryName = "Ecuador" },
            new Country { Id=idCounter++, CountryCode="EGY", CountryName = "Egypt" },
            new Country { Id=idCounter++, CountryCode="SLV", CountryName = "El Salvador" },
            new Country { Id=idCounter++, CountryCode="GNQ", CountryName = "Equatorial Guinea" },
            new Country { Id=idCounter++, CountryCode="ERI", CountryName = "Eritrea" },
            new Country { Id=idCounter++, CountryCode="EST", CountryName = "Estonia" },
            new Country { Id=idCounter++, CountryCode="SWZ", CountryName = "Eswatini" },
            new Country { Id=idCounter++, CountryCode="ETH", CountryName = "Ethiopia" },
            new Country { Id=idCounter++, CountryCode="FLK", CountryName = "Falkland Islands (Malvinas)" },
            new Country { Id=idCounter++, CountryCode="FRO", CountryName = "Faroe Islands" },
            new Country { Id=idCounter++, CountryCode="FJI", CountryName = "Fiji" },
            new Country { Id=idCounter++, CountryCode="FIN", CountryName = "Finland" },
            new Country { Id=idCounter++, CountryCode="FRA", CountryName = "France" },
            new Country { Id=idCounter++, CountryCode="GUF", CountryName = "French Guiana" },
            new Country { Id=idCounter++, CountryCode="PYF", CountryName = "French Polynesia" },
            new Country { Id=idCounter++, CountryCode="ATF", CountryName = "French Southern Territories" },
            new Country { Id=idCounter++, CountryCode="GAB", CountryName = "Gabon" },
            new Country { Id=idCounter++, CountryCode="GMB", CountryName = "Gambia" },
            new Country { Id=idCounter++, CountryCode="GEO", CountryName = "Georgia" },
            new Country { Id=idCounter++, CountryCode="DEU", CountryName = "Germany" },
            new Country { Id=idCounter++, CountryCode="GHA", CountryName = "Ghana" },
            new Country { Id=idCounter++, CountryCode="GIB", CountryName = "Gibraltar" },
            new Country { Id=idCounter++, CountryCode="GRC", CountryName = "Greece" },
            new Country { Id=idCounter++, CountryCode="GRL", CountryName = "Greenland" },
            new Country { Id=idCounter++, CountryCode="GRD", CountryName = "Grenada" },
            new Country { Id=idCounter++, CountryCode="GLP", CountryName = "Guadeloupe" },
            new Country { Id=idCounter++, CountryCode="GUM", CountryName = "Guam" },
            new Country { Id=idCounter++, CountryCode="GTM", CountryName = "Guatemala" },
            new Country { Id=idCounter++, CountryCode="GGY", CountryName = "Guernsey" },
            new Country { Id=idCounter++, CountryCode="GIN", CountryName = "Guinea" },
            new Country { Id=idCounter++, CountryCode="GNB", CountryName = "Guinea-Bissau" },
            new Country { Id=idCounter++, CountryCode="GUY", CountryName = "Guyana" },
            new Country { Id=idCounter++, CountryCode="HTI", CountryName = "Haiti" },
            new Country { Id=idCounter++, CountryCode="HMD", CountryName = "Heard Island and McDonald Islands" },
            new Country { Id=idCounter++, CountryCode="VAT", CountryName = "Holy See" },
            new Country { Id=idCounter++, CountryCode="HND", CountryName = "Honduras" },
            new Country { Id=idCounter++, CountryCode="HKG", CountryName = "Hong Kong" },
            new Country { Id=idCounter++, CountryCode="HUN", CountryName = "Hungary" },
            new Country { Id=idCounter++, CountryCode="ISL", CountryName = "Iceland" },
            new Country { Id=idCounter++, CountryCode="IND", CountryName = "India" },
            new Country { Id=idCounter++, CountryCode="IDN", CountryName = "Indonesia" },
            new Country { Id=idCounter++, CountryCode="IRN", CountryName = "Iran" },
            new Country { Id=idCounter++, CountryCode="IRQ", CountryName = "Iraq" },
            new Country { Id=idCounter++, CountryCode="IRL", CountryName = "Ireland" },
            new Country { Id=idCounter++, CountryCode="ISR", CountryName = "Israel" },
            new Country { Id=idCounter++, CountryCode="ITA", CountryName = "Italy" },
            new Country { Id=idCounter++, CountryCode="JAM", CountryName = "Jamaica" },
            new Country { Id=idCounter++, CountryCode="JPN", CountryName = "Japan" },
            new Country { Id=idCounter++, CountryCode="JOR", CountryName = "Jordan" },
            new Country { Id=idCounter++, CountryCode="KAZ", CountryName = "Kazakhstan" },
            new Country { Id=idCounter++, CountryCode="KEN", CountryName = "Kenya" },
            new Country { Id=idCounter++, CountryCode="KIR", CountryName = "Kiribati" },
            new Country { Id=idCounter++, CountryCode="KWT", CountryName = "Kuwait" },
            new Country { Id=idCounter++, CountryCode="KGZ", CountryName = "Kyrgyzstan" },
            new Country { Id=idCounter++, CountryCode="LAO", CountryName = "Laos" },
            new Country { Id=idCounter++, CountryCode="LVA", CountryName = "Latvia" },
            new Country { Id=idCounter++, CountryCode="LBN", CountryName = "Lebanon" },
            new Country { Id=idCounter++, CountryCode="LSO", CountryName = "Lesotho" },
            new Country { Id=idCounter++, CountryCode="LBR", CountryName = "Liberia" },
            new Country { Id=idCounter++, CountryCode="LBY", CountryName = "Libya" },
            new Country { Id=idCounter++, CountryCode="LIE", CountryName = "Liechtenstein" },
            new Country { Id=idCounter++, CountryCode="LTU", CountryName = "Lithuania" },
            new Country { Id=idCounter++, CountryCode="LUX", CountryName = "Luxembourg" },
            new Country { Id=idCounter++, CountryCode="MDG", CountryName = "Madagascar" },
            new Country { Id=idCounter++, CountryCode="MWI", CountryName = "Malawi" },
            new Country { Id=idCounter++, CountryCode="MYS", CountryName = "Malaysia" },
            new Country { Id=idCounter++, CountryCode="MDV", CountryName = "Maldives" },
            new Country { Id=idCounter++, CountryCode="MLI", CountryName = "Mali" },
            new Country { Id=idCounter++, CountryCode="MLT", CountryName = "Malta" },
            new Country { Id=idCounter++, CountryCode="MHL", CountryName = "Marshall Islands" },
            new Country { Id=idCounter++, CountryCode="MRT", CountryName = "Mauritania" },
            new Country { Id=idCounter++, CountryCode="MUS", CountryName = "Mauritius" },
            new Country { Id=idCounter++, CountryCode="MEX", CountryName = "Mexico" },
            new Country { Id=idCounter++, CountryCode="FSM", CountryName = "Micronesia" },
            new Country { Id=idCounter++, CountryCode="MDA", CountryName = "Moldova" },
            new Country { Id=idCounter++, CountryCode="MCO", CountryName = "Monaco" },
            new Country { Id=idCounter++, CountryCode="MNG", CountryName = "Mongolia" },
            new Country { Id=idCounter++, CountryCode="MNE", CountryName = "Montenegro" },
            new Country { Id=idCounter++, CountryCode="MAR", CountryName = "Morocco" },
            new Country { Id=idCounter++, CountryCode="MOZ", CountryName = "Mozambique" },
            new Country { Id=idCounter++, CountryCode="MMR", CountryName = "Myanmar" },
            new Country { Id=idCounter++, CountryCode="NAM", CountryName = "Namibia" },
            new Country { Id=idCounter++, CountryCode="NRU", CountryName = "Nauru" },
            new Country { Id=idCounter++, CountryCode="NPL", CountryName = "Nepal" },
            new Country { Id=idCounter++, CountryCode="NLD", CountryName = "Netherlands" },
            new Country { Id=idCounter++, CountryCode="NZL", CountryName = "New Zealand" },
            new Country { Id=idCounter++, CountryCode="NIC", CountryName = "Nicaragua" },
            new Country { Id=idCounter++, CountryCode="NER", CountryName = "Niger" },
            new Country { Id=idCounter++, CountryCode="NGA", CountryName = "Nigeria" },
            new Country { Id=idCounter++, CountryCode="PRK", CountryName = "North Korea" },
            new Country { Id=idCounter++, CountryCode="MKD", CountryName = "North Macedonia" },
            new Country { Id=idCounter++, CountryCode="NOR", CountryName = "Norway" },
            new Country { Id=idCounter++, CountryCode="OMN", CountryName = "Oman" },
            new Country { Id=idCounter++, CountryCode="PAK", CountryName = "Pakistan" },
            new Country { Id=idCounter++, CountryCode="PLW", CountryName = "Palau" },
            new Country { Id=idCounter++, CountryCode="PSE", CountryName = "Palestine State" },
            new Country { Id=idCounter++, CountryCode="PAN", CountryName = "Panama" },
            new Country { Id=idCounter++, CountryCode="PNG", CountryName = "Papua New Guinea" },
            new Country { Id=idCounter++, CountryCode="PRY", CountryName = "Paraguay" },
            new Country { Id=idCounter++, CountryCode="PER", CountryName = "Peru" },
            new Country { Id=idCounter++, CountryCode="PHL", CountryName = "Philippines" },
            new Country { Id=idCounter++, CountryCode="POL", CountryName = "Poland" },
            new Country { Id=idCounter++, CountryCode="PRT", CountryName = "Portugal" },
            new Country { Id=idCounter++, CountryCode="QAT", CountryName = "Qatar" },
            new Country { Id=idCounter++, CountryCode="ROU", CountryName = "Romania" },
            new Country { Id=idCounter++, CountryCode="RUS", CountryName = "Russia" },
            new Country { Id=idCounter++, CountryCode="RWA", CountryName = "Rwanda" },
            new Country { Id=idCounter++, CountryCode="KNA", CountryName = "Saint Kitts and Nevis" },
            new Country { Id=idCounter++, CountryCode="LCA", CountryName = "Saint Lucia" },
            new Country { Id=idCounter++, CountryCode="VCT", CountryName = "Saint Vincent and the Grenadines" },
            new Country { Id=idCounter++, CountryCode="WSM", CountryName = "Samoa" },
            new Country { Id=idCounter++, CountryCode="SMR", CountryName = "San Marino" },
            new Country { Id=idCounter++, CountryCode="STP", CountryName = "Sao Tome and Principe" },
            new Country { Id=idCounter++, CountryCode="SAU", CountryName = "Saudi Arabia" },
            new Country { Id=idCounter++, CountryCode="SEN", CountryName = "Senegal" },
            new Country { Id=idCounter++, CountryCode="SRB", CountryName = "Serbia" },
            new Country { Id=idCounter++, CountryCode="SYC", CountryName = "Seychelles" },
            new Country { Id=idCounter++, CountryCode="SLE", CountryName = "Sierra Leone" },
            new Country { Id=idCounter++, CountryCode="SGP", CountryName = "Singapore" },
            new Country { Id=idCounter++, CountryCode="SVK", CountryName = "Slovakia" },
            new Country { Id=idCounter++, CountryCode="SVN", CountryName = "Slovenia" },
            new Country { Id=idCounter++, CountryCode="SLB", CountryName = "Solomon Islands" },
            new Country { Id=idCounter++, CountryCode="SOM", CountryName = "Somalia" },
            new Country { Id=idCounter++, CountryCode="ZAF", CountryName = "South Africa" },
            new Country { Id=idCounter++, CountryCode="KOR", CountryName = "South Korea" },
            new Country { Id=idCounter++, CountryCode="SSD", CountryName = "South Sudan" },
            new Country { Id=idCounter++, CountryCode="ESP", CountryName = "Spain" },
            new Country { Id=idCounter++, CountryCode="LKA", CountryName = "Sri Lanka" },
            new Country { Id=idCounter++, CountryCode="SDN", CountryName = "Sudan" },
            new Country { Id=idCounter++, CountryCode="SUR", CountryName = "Suriname" },
            new Country { Id=idCounter++, CountryCode="SWE", CountryName = "Sweden" },
            new Country { Id=idCounter++, CountryCode="CHE", CountryName = "Switzerland" },
            new Country { Id=idCounter++, CountryCode="SYR", CountryName = "Syria" },
            new Country { Id=idCounter++, CountryCode="TJK", CountryName = "Tajikistan" },
            new Country { Id=idCounter++, CountryCode="TZA", CountryName = "Tanzania" },
            new Country { Id=idCounter++, CountryCode="THA", CountryName = "Thailand" },
            new Country { Id=idCounter++, CountryCode="TLS", CountryName = "Timor-Leste" },
            new Country { Id=idCounter++, CountryCode="TGO", CountryName = "Togo" },
            new Country { Id=idCounter++, CountryCode="TON", CountryName = "Tonga" },
            new Country { Id=idCounter++, CountryCode="TTO", CountryName = "Trinidad and Tobago" },
            new Country { Id=idCounter++, CountryCode="TUN", CountryName = "Tunisia" },
            new Country { Id=idCounter++, CountryCode="TUR", CountryName = "Turkey" },
            new Country { Id=idCounter++, CountryCode="TKM", CountryName = "Turkmenistan" },
            new Country { Id=idCounter++, CountryCode="TUV", CountryName = "Tuvalu" },
            new Country { Id=idCounter++, CountryCode="UGA", CountryName = "Uganda" },
            new Country { Id=idCounter++, CountryCode="UKR", CountryName = "Ukraine" },
            new Country { Id=idCounter++, CountryCode="ARE", CountryName = "United Arab Emirates" },
            new Country { Id=idCounter++, CountryCode="GBR", CountryName = "United Kingdom" },
            new Country { Id=idCounter++, CountryCode="USA", CountryName = "United States of America" },
            new Country { Id=idCounter++, CountryCode="URY", CountryName = "Uruguay" },
            new Country { Id=idCounter++, CountryCode="UZB", CountryName = "Uzbekistan" },
            new Country { Id=idCounter++, CountryCode="VUT", CountryName = "Vanuatu" },
            new Country { Id=idCounter++, CountryCode="VEN", CountryName = "Venezuela" },
            new Country { Id=idCounter++, CountryCode="VNM", CountryName = "Vietnam" },
            new Country { Id=idCounter++, CountryCode="YEM", CountryName = "Yemen" },
            new Country { Id=idCounter++, CountryCode="ZMB", CountryName = "Zambia" },
            new Country { Id=idCounter++, CountryCode="ZWE", CountryName = "Zimbabwe" }
            };
    }
}
