using SkyVault.WebApi.Backend.Models;

namespace SkyVault.WebApi.Backend.Seeds
{
    public class CountrySeedData
    {
        private static int idCounter = 1;

        public static readonly List<Country> countries = new List<Country>
        {
            new Country { Id=idCounter++, CountryName = "Afghanistan" },
            new Country { Id=idCounter++, CountryName = "Albania" },
            new Country { Id=idCounter++, CountryName = "Algeria" },
            new Country { Id=idCounter++, CountryName = "Andorra" },
            new Country { Id=idCounter++, CountryName = "Angola" },
            new Country { Id=idCounter++, CountryName = "Antigua and Barbuda" },
            new Country { Id=idCounter++, CountryName = "Argentina" },
            new Country { Id=idCounter++, CountryName = "Armenia" },
            new Country { Id=idCounter++, CountryName = "Australia" },
            new Country { Id=idCounter++, CountryName = "Austria" },
            new Country { Id=idCounter++, CountryName = "Azerbaijan" },
            new Country { Id=idCounter++, CountryName = "Bahamas" },
            new Country { Id=idCounter++, CountryName = "Bahrain" },
            new Country { Id=idCounter++, CountryName = "Bangladesh" },
            new Country { Id=idCounter++, CountryName = "Barbados" },
            new Country { Id=idCounter++, CountryName = "Belarus" },
            new Country { Id=idCounter++, CountryName = "Belgium" },
            new Country { Id=idCounter++, CountryName = "Belize" },
            new Country { Id=idCounter++, CountryName = "Benin" },
            new Country { Id=idCounter++, CountryName = "Bhutan" },
            new Country { Id=idCounter++, CountryName = "Bolivia" },
            new Country { Id=idCounter++, CountryName = "Bosnia and Herzegovina" },
            new Country { Id=idCounter++, CountryName = "Botswana" },
            new Country { Id=idCounter++, CountryName = "Brazil" },
            new Country { Id=idCounter++, CountryName = "Brunei" },
            new Country { Id=idCounter++, CountryName = "Bulgaria" },
            new Country { Id=idCounter++, CountryName = "Burkina Faso" },
            new Country { Id=idCounter++, CountryName = "Burundi" },
            new Country { Id=idCounter++, CountryName = "Cabo Verde" },
            new Country { Id=idCounter++, CountryName = "Cambodia" },
            new Country { Id=idCounter++, CountryName = "Cameroon" },
            new Country { Id=idCounter++, CountryName = "Canada" },
            new Country { Id=idCounter++, CountryName = "Central African Republic" },
            new Country { Id=idCounter++, CountryName = "Chad" },
            new Country { Id=idCounter++, CountryName = "Chile" },
            new Country { Id=idCounter++, CountryName = "China" },
            new Country { Id=idCounter++, CountryName = "Colombia" },
            new Country { Id=idCounter++, CountryName = "Comoros" },
            new Country { Id=idCounter++, CountryName = "Congo (Congo-Brazzaville)" },
            new Country { Id=idCounter++, CountryName = "Costa Rica" },
            new Country { Id=idCounter++, CountryName = "Croatia" },
            new Country { Id=idCounter++, CountryName = "Cuba" },
            new Country { Id=idCounter++, CountryName = "Cyprus" },
            new Country { Id=idCounter++, CountryName = "Czechia (Czech Republic)" },
            new Country { Id=idCounter++, CountryName = "Democratic Republic of the Congo" },
            new Country { Id=idCounter++, CountryName = "Denmark" },
            new Country { Id=idCounter++, CountryName = "Djibouti" },
            new Country { Id=idCounter++, CountryName = "Dominica" },
            new Country { Id=idCounter++, CountryName = "Dominican Republic" },
            new Country { Id=idCounter++, CountryName = "Ecuador" },
            new Country { Id=idCounter++, CountryName = "Egypt" },
            new Country { Id=idCounter++, CountryName = "El Salvador" },
            new Country { Id=idCounter++, CountryName = "Equatorial Guinea" },
            new Country { Id=idCounter++, CountryName = "Eritrea" },
            new Country { Id=idCounter++, CountryName = "Estonia" },
            new Country { Id=idCounter++, CountryName = "Swaziland" },
            new Country { Id=idCounter++, CountryName = "Ethiopia" },
            new Country { Id=idCounter++, CountryName = "Fiji" },
            new Country { Id=idCounter++, CountryName = "Finland" },
            new Country { Id=idCounter++, CountryName = "France" },
            new Country { Id=idCounter++, CountryName = "Gabon" },
            new Country { Id=idCounter++, CountryName = "Gambia" },
            new Country { Id=idCounter++, CountryName = "Georgia" },
            new Country { Id=idCounter++, CountryName = "Germany" },
            new Country { Id=idCounter++, CountryName = "Ghana" },
            new Country { Id=idCounter++, CountryName = "Greece" },
            new Country { Id=idCounter++, CountryName = "Grenada" },
            new Country { Id=idCounter++, CountryName = "Guatemala" },
            new Country { Id=idCounter++, CountryName = "Guinea" },
            new Country { Id=idCounter++, CountryName = "Guinea-Bissau" },
            new Country { Id=idCounter++, CountryName = "Guyana" },
            new Country { Id=idCounter++, CountryName = "Haiti" },
            new Country { Id=idCounter++, CountryName = "Holy See" },
            new Country { Id=idCounter++, CountryName = "Honduras" },
            new Country { Id=idCounter++, CountryName = "Hungary" },
            new Country { Id=idCounter++, CountryName = "Iceland" },
            new Country { Id=idCounter++, CountryName = "India" },
            new Country { Id=idCounter++, CountryName = "Indonesia" },
            new Country { Id=idCounter++, CountryName = "Iran" },
            new Country { Id=idCounter++, CountryName = "Iraq" },
            new Country { Id=idCounter++, CountryName = "Ireland" },
            new Country { Id=idCounter++, CountryName = "Israel" },
            new Country { Id=idCounter++, CountryName = "Italy" },
            new Country { Id=idCounter++, CountryName = "Jamaica" },
            new Country { Id=idCounter++, CountryName = "Japan" },
            new Country { Id=idCounter++, CountryName = "Jordan" },
            new Country { Id=idCounter++, CountryName = "Kazakhstan" },
            new Country { Id=idCounter++, CountryName = "Kenya" },
            new Country { Id=idCounter++, CountryName = "Kiribati" },
            new Country { Id=idCounter++, CountryName = "Kuwait" },
            new Country { Id=idCounter++, CountryName = "Kyrgyzstan" },
            new Country { Id=idCounter++, CountryName = "Laos" },
            new Country { Id=idCounter++, CountryName = "Latvia" },
            new Country { Id=idCounter++, CountryName = "Lebanon" },
            new Country { Id=idCounter++, CountryName = "Lesotho" },
            new Country { Id=idCounter++, CountryName = "Liberia" },
            new Country { Id=idCounter++, CountryName = "Libya" },
            new Country { Id=idCounter++, CountryName = "Liechtenstein" },
            new Country { Id=idCounter++, CountryName = "Lithuania" },
            new Country { Id=idCounter++, CountryName = "Luxembourg" },
            new Country { Id=idCounter++, CountryName = "Madagascar" },
            new Country { Id=idCounter++, CountryName = "Malawi" },
            new Country { Id=idCounter++, CountryName = "Malaysia" },
            new Country { Id=idCounter++, CountryName = "Maldives" },
            new Country { Id=idCounter++, CountryName = "Mali" },
            new Country { Id=idCounter++, CountryName = "Malta" },
            new Country { Id=idCounter++, CountryName = "Marshall Islands" },
            new Country { Id=idCounter++, CountryName = "Mauritania" },
            new Country { Id=idCounter++, CountryName = "Mauritius" },
            new Country { Id=idCounter++, CountryName = "Mexico" },
            new Country { Id=idCounter++, CountryName = "Micronesia" },
            new Country { Id=idCounter++, CountryName = "Moldova" },
            new Country { Id=idCounter++, CountryName = "Monaco" },
            new Country { Id=idCounter++, CountryName = "Mongolia" },
            new Country { Id=idCounter++, CountryName = "Montenegro" },
            new Country { Id=idCounter++, CountryName = "Morocco" },
            new Country { Id=idCounter++, CountryName = "Mozambique" },
            new Country { Id=idCounter++, CountryName = "Myanmar" },
            new Country { Id=idCounter++, CountryName = "Namibia" },
            new Country { Id=idCounter++, CountryName = "Nauru" },
            new Country { Id=idCounter++, CountryName = "Nepal" },
            new Country { Id=idCounter++, CountryName = "Netherlands" },
            new Country { Id=idCounter++, CountryName = "New Zealand" },
            new Country { Id=idCounter++, CountryName = "Nicaragua" },
            new Country { Id=idCounter++, CountryName = "Niger" },
            new Country { Id=idCounter++, CountryName = "Nigeria" },
            new Country { Id=idCounter++, CountryName = "North Korea" },
            new Country { Id=idCounter++, CountryName = "North Macedonia" },
            new Country { Id=idCounter++, CountryName = "Norway" },
            new Country { Id=idCounter++, CountryName = "Oman" },
            new Country { Id=idCounter++, CountryName = "Pakistan" },
            new Country { Id=idCounter++, CountryName = "Palau" },
            new Country { Id=idCounter++, CountryName = "Palestine State" },
            new Country { Id=idCounter++, CountryName = "Panama" },
            new Country { Id=idCounter++, CountryName = "Papua New Guinea" },
            new Country { Id=idCounter++, CountryName = "Paraguay" },
            new Country { Id=idCounter++, CountryName = "Peru" },
            new Country { Id=idCounter++, CountryName = "Philippines" },
            new Country { Id=idCounter++, CountryName = "Poland" },
            new Country { Id=idCounter++, CountryName = "Portugal" },
            new Country { Id=idCounter++, CountryName = "Qatar" },
            new Country { Id=idCounter++, CountryName = "Romania" },
            new Country { Id=idCounter++, CountryName = "Russia" },
            new Country { Id=idCounter++, CountryName = "Rwanda" },
            new Country { Id=idCounter++, CountryName = "Saint Kitts and Nevis" },
            new Country { Id=idCounter++, CountryName = "Saint Lucia" },
            new Country { Id=idCounter++, CountryName = "Saint Vincent and the Grenadines" },
            new Country { Id=idCounter++, CountryName = "Samoa" },
            new Country { Id=idCounter++, CountryName = "San Marino" },
            new Country { Id=idCounter++, CountryName = "Sao Tome and Principe" },
            new Country { Id=idCounter++, CountryName = "Saudi Arabia" },
            new Country { Id=idCounter++, CountryName = "Senegal" },
            new Country { Id=idCounter++, CountryName = "Serbia" },
            new Country { Id=idCounter++, CountryName = "Seychelles" },
            new Country { Id=idCounter++, CountryName = "Sierra Leone" },
            new Country { Id=idCounter++, CountryName = "Singapore" },
            new Country { Id=idCounter++, CountryName = "Slovakia" },
            new Country { Id=idCounter++, CountryName = "Slovenia" },
            new Country { Id=idCounter++, CountryName = "Solomon Islands" },
            new Country { Id=idCounter++, CountryName = "Somalia" },
            new Country { Id=idCounter++, CountryName = "South Africa" },
            new Country { Id=idCounter++, CountryName = "South Korea" },
            new Country { Id=idCounter++, CountryName = "South Sudan" },
            new Country { Id=idCounter++, CountryName = "Spain" },
            new Country { Id=idCounter++, CountryName = "Sri Lanka" },
            new Country { Id=idCounter++, CountryName = "Sudan" },
            new Country { Id=idCounter++, CountryName = "Suriname" },
            new Country { Id=idCounter++, CountryName = "Sweden" },
            new Country { Id=idCounter++, CountryName = "Switzerland" },
            new Country { Id=idCounter++, CountryName = "Syria" },
            new Country { Id=idCounter++, CountryName = "Tajikistan" },
            new Country { Id=idCounter++, CountryName = "Tanzania" },
            new Country { Id=idCounter++, CountryName = "Thailand" },
            new Country { Id=idCounter++, CountryName = "Timor-Leste" },
            new Country { Id=idCounter++, CountryName = "Togo" },
            new Country { Id=idCounter++, CountryName = "Tonga" },
            new Country { Id=idCounter++, CountryName = "Trinidad and Tobago" },
            new Country { Id=idCounter++, CountryName = "Tunisia" },
            new Country { Id=idCounter++, CountryName = "Turkey" },
            new Country { Id=idCounter++, CountryName = "Turkmenistan" },
            new Country { Id=idCounter++, CountryName = "Tuvalu" },
            new Country { Id=idCounter++, CountryName = "Uganda" },
            new Country { Id=idCounter++, CountryName = "Ukraine" },
            new Country { Id=idCounter++, CountryName = "United Arab Emirates" },
            new Country { Id=idCounter++, CountryName = "United Kingdom" },
            new Country { Id=idCounter++, CountryName = "United States of America" },
            new Country { Id=idCounter++, CountryName = "Uruguay" },
            new Country { Id=idCounter++, CountryName = "Uzbekistan" },
            new Country { Id=idCounter++, CountryName = "Vanuatu" },
            new Country { Id=idCounter++, CountryName = "Venezuela" },
            new Country { Id=idCounter++, CountryName = "Vietnam" },
            new Country { Id=idCounter++, CountryName = "Yemen" },
            new Country { Id=idCounter++, CountryName = "Zambia" },
            new Country { Id=idCounter++, CountryName = "Zimbabwe" }
        };
    }
}
