using SkyVault.WebApi.Backend.Models;

namespace SkyVault.WebApi.Backend.Seeds
{
    public class NationalitySeedData
    {
        private static int idCounter = 1;

        public static readonly List<Nationality> nationalities = new List<Nationality>
        {
            new Nationality { Id=idCounter++, NationalityName = "Afghan" },
            new Nationality { Id=idCounter++, NationalityName = "Albanian" },
            new Nationality { Id=idCounter++, NationalityName = "Algerian" },
            new Nationality { Id=idCounter++, NationalityName = "American" },
            new Nationality { Id=idCounter++, NationalityName = "Andorran" },
            new Nationality { Id=idCounter++, NationalityName = "Angolan" },
            new Nationality { Id=idCounter++, NationalityName = "Antiguans" },
            new Nationality { Id=idCounter++, NationalityName = "Argentinean" },
            new Nationality { Id=idCounter++, NationalityName = "Armenian" },
            new Nationality { Id=idCounter++, NationalityName = "Australian" },
            new Nationality { Id=idCounter++, NationalityName = "Austrian" },
            new Nationality { Id=idCounter++, NationalityName = "Azerbaijani" },
            new Nationality { Id=idCounter++, NationalityName = "Bahamian" },
            new Nationality { Id=idCounter++, NationalityName = "Bahraini" },
            new Nationality { Id=idCounter++, NationalityName = "Bangladeshi" },
            new Nationality { Id=idCounter++, NationalityName = "Barbadian" },
            new Nationality { Id=idCounter++, NationalityName = "Belarusian" },
            new Nationality { Id=idCounter++, NationalityName = "Belgian" },
            new Nationality { Id=idCounter++, NationalityName = "Belizean" },
            new Nationality { Id=idCounter++, NationalityName = "Beninese" },
            new Nationality { Id=idCounter++, NationalityName = "Bhutanese" },
            new Nationality { Id=idCounter++, NationalityName = "Bolivian" },
            new Nationality { Id=idCounter++, NationalityName = "Bosnian" },
            new Nationality { Id=idCounter++, NationalityName = "Botswanan" },
            new Nationality { Id=idCounter++, NationalityName = "Brazilian" },
            new Nationality { Id=idCounter++, NationalityName = "British" },
            new Nationality { Id=idCounter++, NationalityName = "Bruneian" },
            new Nationality { Id=idCounter++, NationalityName = "Bulgarian" },
            new Nationality { Id=idCounter++, NationalityName = "Burkinabe" },
            new Nationality { Id=idCounter++, NationalityName = "Burundian" },
            new Nationality { Id=idCounter++, NationalityName = "Cambodian" },
            new Nationality { Id=idCounter++, NationalityName = "Cameroonian" },
            new Nationality { Id=idCounter++, NationalityName = "Canadian" },
            new Nationality { Id=idCounter++, NationalityName = "Cape Verdean" },
            new Nationality { Id=idCounter++, NationalityName = "Central African" },
            new Nationality { Id=idCounter++, NationalityName = "Chadian" },
            new Nationality { Id=idCounter++, NationalityName = "Chilean" },
            new Nationality { Id=idCounter++, NationalityName = "Chinese" },
            new Nationality { Id=idCounter++, NationalityName = "Colombian" },
            new Nationality { Id=idCounter++, NationalityName = "Comoran" },
            new Nationality { Id=idCounter++, NationalityName = "Congolese" },
            new Nationality { Id=idCounter++, NationalityName = "Costa Rican" },
            new Nationality { Id=idCounter++, NationalityName = "Croatian" },
            new Nationality { Id=idCounter++, NationalityName = "Cuban" },
            new Nationality { Id=idCounter++, NationalityName = "Cypriot" },
            new Nationality { Id=idCounter++, NationalityName = "Czech" },
            new Nationality { Id=idCounter++, NationalityName = "Danish" },
            new Nationality { Id=idCounter++, NationalityName = "Djiboutian" },
            new Nationality { Id=idCounter++, NationalityName = "Dominican" },
            new Nationality { Id=idCounter++, NationalityName = "Dutch" },
            new Nationality { Id=idCounter++, NationalityName = "East Timorese" },
            new Nationality { Id=idCounter++, NationalityName = "Ecuadorean" },
            new Nationality { Id=idCounter++, NationalityName = "Egyptian" },
            new Nationality { Id=idCounter++, NationalityName = "Emirian" },
            new Nationality { Id=idCounter++, NationalityName = "Equatorial Guinean" },
            new Nationality { Id=idCounter++, NationalityName = "Eritrean" },
            new Nationality { Id=idCounter++, NationalityName = "Estonian" },
            new Nationality { Id=idCounter++, NationalityName = "Ethiopian" },
            new Nationality { Id=idCounter++, NationalityName = "Fijian" },
            new Nationality { Id=idCounter++, NationalityName = "Filipino" },
            new Nationality { Id=idCounter++, NationalityName = "Finnish" },
            new Nationality { Id=idCounter++, NationalityName = "French" },
            new Nationality { Id=idCounter++, NationalityName = "Gabonese" },
            new Nationality { Id=idCounter++, NationalityName = "Gambian" },
            new Nationality { Id=idCounter++, NationalityName = "Georgian" },
            new Nationality { Id=idCounter++, NationalityName = "German" },
            new Nationality { Id=idCounter++, NationalityName = "Ghanaian" },
            new Nationality { Id=idCounter++, NationalityName = "Greek" },
            new Nationality { Id=idCounter++, NationalityName = "Grenadian" },
            new Nationality { Id=idCounter++, NationalityName = "Guatemalan" },
            new Nationality { Id=idCounter++, NationalityName = "Guinea-Bissauan" },
            new Nationality { Id=idCounter++, NationalityName = "Guinean" },
            new Nationality { Id=idCounter++, NationalityName = "Guyanese" },
            new Nationality { Id=idCounter++, NationalityName = "Haitian" },
            new Nationality { Id=idCounter++, NationalityName = "Herzegovinian" },
            new Nationality { Id=idCounter++, NationalityName = "Honduran" },
            new Nationality { Id=idCounter++, NationalityName = "Hungarian" },
            new Nationality { Id=idCounter++, NationalityName = "I-Kiribati" },
            new Nationality { Id=idCounter++, NationalityName = "Icelander" },
            new Nationality { Id=idCounter++, NationalityName = "Indian" },
            new Nationality { Id=idCounter++, NationalityName = "Indonesian" },
            new Nationality { Id=idCounter++, NationalityName = "Iranian" },
            new Nationality { Id=idCounter++, NationalityName = "Iraqi" },
            new Nationality { Id=idCounter++, NationalityName = "Irish" },
            new Nationality { Id=idCounter++, NationalityName = "Israeli" },
            new Nationality { Id=idCounter++, NationalityName = "Italian" },
            new Nationality { Id=idCounter++, NationalityName = "Ivorian" },
            new Nationality { Id=idCounter++, NationalityName = "Jamaican" },
            new Nationality { Id=idCounter++, NationalityName = "Japanese" },
            new Nationality { Id=idCounter++, NationalityName = "Jordanian" },
            new Nationality { Id=idCounter++, NationalityName = "Kazakhstani" },
            new Nationality { Id=idCounter++, NationalityName = "Kenyan" },
            new Nationality { Id=idCounter++, NationalityName = "Kittian and Nevisian" },
            new Nationality { Id=idCounter++, NationalityName = "Kuwaiti" },
            new Nationality { Id=idCounter++, NationalityName = "Kyrgyz" },
            new Nationality { Id=idCounter++, NationalityName = "Laotian" },
            new Nationality { Id=idCounter++, NationalityName = "Latvian" },
            new Nationality { Id=idCounter++, NationalityName = "Lebanese" },
            new Nationality { Id=idCounter++, NationalityName = "Liberian" },
            new Nationality { Id=idCounter++, NationalityName = "Libyan" },
            new Nationality { Id=idCounter++, NationalityName = "Liechtensteiner" },
            new Nationality { Id=idCounter++, NationalityName = "Lithuanian" },
            new Nationality { Id=idCounter++, NationalityName = "Luxembourger" },
            new Nationality { Id=idCounter++, NationalityName = "Malagasy" },
            new Nationality { Id=idCounter++, NationalityName = "Malawian" },
            new Nationality { Id=idCounter++, NationalityName = "Malaysian" },
            new Nationality { Id=idCounter++, NationalityName = "Maldivan" },
            new Nationality { Id=idCounter++, NationalityName = "Malian" },
            new Nationality { Id=idCounter++, NationalityName = "Maltese" },
            new Nationality { Id=idCounter++, NationalityName = "Marshallese" },
            new Nationality { Id=idCounter++, NationalityName = "Mauritanian" },
            new Nationality { Id=idCounter++, NationalityName = "Mauritian" },
            new Nationality { Id=idCounter++, NationalityName = "Mexican" },
            new Nationality { Id=idCounter++, NationalityName = "Micronesian" },
            new Nationality { Id=idCounter++, NationalityName = "Moldovan" },
            new Nationality { Id=idCounter++, NationalityName = "Monacan" },
            new Nationality { Id=idCounter++, NationalityName = "Mongolian" },
            new Nationality { Id=idCounter++, NationalityName = "Montenegrin" },
            new Nationality { Id=idCounter++, NationalityName = "Moroccan" },
            new Nationality { Id=idCounter++, NationalityName = "Mosotho" },
            new Nationality { Id=idCounter++, NationalityName = "Motswana" },
            new Nationality { Id=idCounter++, NationalityName = "Mozambican" },
            new Nationality { Id=idCounter++, NationalityName = "Namibian" },
            new Nationality { Id=idCounter++, NationalityName = "Nauruan" },
            new Nationality { Id=idCounter++, NationalityName = "Nepalese" },
            new Nationality { Id=idCounter++, NationalityName = "Netherlander" },
            new Nationality { Id=idCounter++, NationalityName = "New Zealander" },
            new Nationality { Id=idCounter++, NationalityName = "Nicaraguan" },
            new Nationality { Id=idCounter++, NationalityName = "Nigerian" },
            new Nationality { Id=idCounter++, NationalityName = "North Korean" },
            new Nationality { Id=idCounter++, NationalityName = "Northern Irish" },
            new Nationality { Id=idCounter++, NationalityName = "Norwegian" },
            new Nationality { Id=idCounter++, NationalityName = "Omani" },
            new Nationality { Id=idCounter++, NationalityName = "Pakistani" },
            new Nationality { Id=idCounter++, NationalityName = "Palauan" },
            new Nationality { Id=idCounter++, NationalityName = "Panamanian" },
            new Nationality { Id=idCounter++, NationalityName = "Papua New Guinean" },
            new Nationality { Id=idCounter++, NationalityName = "Paraguayan" },
            new Nationality { Id=idCounter++, NationalityName = "Peruvian" },
            new Nationality { Id=idCounter++, NationalityName = "Polish" },
            new Nationality { Id=idCounter++, NationalityName = "Portuguese" },
            new Nationality { Id=idCounter++, NationalityName = "Qatari" },
            new Nationality { Id=idCounter++, NationalityName = "Romanian" },
            new Nationality { Id=idCounter++, NationalityName = "Russian" },
            new Nationality { Id=idCounter++, NationalityName = "Rwandan" },
            new Nationality { Id=idCounter++, NationalityName = "Saint Lucian" },
            new Nationality { Id=idCounter++, NationalityName = "Salvadoran" },
            new Nationality { Id=idCounter++, NationalityName = "Samoan" },
            new Nationality { Id=idCounter++, NationalityName = "San Marinese" },
            new Nationality { Id=idCounter++, NationalityName = "Sao Tomean" },
            new Nationality { Id=idCounter++, NationalityName = "Saudi" },
            new Nationality { Id=idCounter++, NationalityName = "Scottish" },
            new Nationality { Id=idCounter++, NationalityName = "Senegalese" },
            new Nationality { Id=idCounter++, NationalityName = "Serbian" },
            new Nationality { Id=idCounter++, NationalityName = "Seychellois" },
            new Nationality { Id=idCounter++, NationalityName = "Sierra Leonean" },
            new Nationality { Id=idCounter++, NationalityName = "Singaporean" },
            new Nationality { Id=idCounter++, NationalityName = "Slovak" },
            new Nationality { Id=idCounter++, NationalityName = "Slovenian" },
            new Nationality { Id=idCounter++, NationalityName = "Solomon Islander" },
            new Nationality { Id=idCounter++, NationalityName = "Somali" },
            new Nationality { Id=idCounter++, NationalityName = "South African" },
            new Nationality { Id=idCounter++, NationalityName = "South Korean" },
            new Nationality { Id=idCounter++, NationalityName = "South Sudanese" },
            new Nationality { Id=idCounter++, NationalityName = "Spanish" },
            new Nationality { Id=idCounter++, NationalityName = "Sri Lankan" },
            new Nationality { Id=idCounter++, NationalityName = "Sudanese" },
            new Nationality { Id=idCounter++, NationalityName = "Surinamer" },
            new Nationality { Id=idCounter++, NationalityName = "Swazi" },
            new Nationality { Id=idCounter++, NationalityName = "Swedish" },
            new Nationality { Id=idCounter++, NationalityName = "Swiss" },
            new Nationality { Id=idCounter++, NationalityName = "Syrian" },
            new Nationality { Id=idCounter++, NationalityName = "Taiwanese" },
            new Nationality { Id=idCounter++, NationalityName = "Tajik" },
            new Nationality { Id=idCounter++, NationalityName = "Tanzanian" },
            new Nationality { Id=idCounter++, NationalityName = "Thai" },
            new Nationality { Id=idCounter++, NationalityName = "Togolese" },
            new Nationality { Id=idCounter++, NationalityName = "Tongan" },
            new Nationality { Id=idCounter++, NationalityName = "Trinidadian or Tobagonian" },
            new Nationality { Id=idCounter++, NationalityName = "Tunisian" },
            new Nationality { Id=idCounter++, NationalityName = "Turkish" },
            new Nationality { Id=idCounter++, NationalityName = "Turkmen" },
            new Nationality { Id=idCounter++, NationalityName = "Tuvaluan" },
            new Nationality { Id=idCounter++, NationalityName = "Ugandan" },
            new Nationality { Id=idCounter++, NationalityName = "Ukrainian" },
            new Nationality { Id=idCounter++, NationalityName = "Uruguayan" },
            new Nationality { Id=idCounter++, NationalityName = "Uzbekistani" },
            new Nationality { Id=idCounter++, NationalityName = "Vanuatuan" },
            new Nationality { Id=idCounter++, NationalityName = "Venezuelan" },
            new Nationality { Id=idCounter++, NationalityName = "Vietnamese" },
            new Nationality { Id=idCounter++, NationalityName = "Yemeni" },
            new Nationality { Id=idCounter++, NationalityName = "Zambian" },
            new Nationality { Id=idCounter++, NationalityName = "Zimbabwean" },
        };
    }
}
