using SkyVault.WebApi.Backend.Models;

namespace SkyVault.WebApi.Backend.Seeds
{
    public class NationalitySeedData
    {
        private static int idCounter = 1;

        public static readonly List<Nationality> nationalities = new List<Nationality>
        {
            new Nationality { Id=idCounter++, NationalityName = "Afghan", NationalityCode = "AFG" },
            new Nationality { Id=idCounter++, NationalityName = "Albanian", NationalityCode = "ALB" },
            new Nationality { Id=idCounter++, NationalityName = "Algerian", NationalityCode = "DZA" },
            new Nationality { Id=idCounter++, NationalityName = "American", NationalityCode = "USA" },
            new Nationality { Id=idCounter++, NationalityName = "Andorran", NationalityCode = "AND" },
            new Nationality { Id=idCounter++, NationalityName = "Angolan", NationalityCode = "AGO" },
            new Nationality { Id=idCounter++, NationalityName = "Antiguans", NationalityCode = "ATG" },
            new Nationality { Id=idCounter++, NationalityName = "Argentinean", NationalityCode = "ARG" },
            new Nationality { Id=idCounter++, NationalityName = "Armenian", NationalityCode = "ARM" },
            new Nationality { Id=idCounter++, NationalityName = "Australian", NationalityCode = "AUS" },
            new Nationality { Id=idCounter++, NationalityName = "Austrian", NationalityCode = "AUT" },
            new Nationality { Id=idCounter++, NationalityName = "Azerbaijani", NationalityCode = "AZE" },
            new Nationality { Id=idCounter++, NationalityName = "Bahamian", NationalityCode = "BHS" },
            new Nationality { Id=idCounter++, NationalityName = "Bahraini", NationalityCode = "BHR" },
            new Nationality { Id=idCounter++, NationalityName = "Bangladeshi", NationalityCode = "BGD" },
            new Nationality { Id=idCounter++, NationalityName = "Barbadian", NationalityCode = "BRB" },
            new Nationality { Id=idCounter++, NationalityName = "Belarusian", NationalityCode = "BLR" },
            new Nationality { Id=idCounter++, NationalityName = "Belgian", NationalityCode = "BEL" },
            new Nationality { Id=idCounter++, NationalityName = "Belizean", NationalityCode = "BLZ" },
            new Nationality { Id=idCounter++, NationalityName = "Beninese", NationalityCode = "BEN" },
            new Nationality { Id=idCounter++, NationalityName = "Bhutanese", NationalityCode = "BTN" },
            new Nationality { Id=idCounter++, NationalityName = "Bolivian", NationalityCode = "BOL" },
            new Nationality { Id=idCounter++, NationalityName = "Bosnian", NationalityCode = "BIH" },
            new Nationality { Id=idCounter++, NationalityName = "Botswanan", NationalityCode = "BWA" },
            new Nationality { Id=idCounter++, NationalityName = "Brazilian", NationalityCode = "BRA" },
            new Nationality { Id=idCounter++, NationalityName = "British", NationalityCode = "GBR" },
            new Nationality { Id=idCounter++, NationalityName = "Bruneian", NationalityCode = "BRN" },
            new Nationality { Id=idCounter++, NationalityName = "Bulgarian", NationalityCode = "BGR" },
            new Nationality { Id=idCounter++, NationalityName = "Burkinabe", NationalityCode = "BFA" },
            new Nationality { Id=idCounter++, NationalityName = "Burundian", NationalityCode = "BDI" },
            new Nationality { Id=idCounter++, NationalityName = "Cambodian", NationalityCode = "KHM" },
            new Nationality { Id=idCounter++, NationalityName = "Cameroonian", NationalityCode = "CMR" },
            new Nationality { Id=idCounter++, NationalityName = "Canadian", NationalityCode = "CAN" },
            new Nationality { Id=idCounter++, NationalityName = "Cape Verdean", NationalityCode = "CPV" },
            new Nationality { Id=idCounter++, NationalityName = "Central African", NationalityCode = "CAF" },
            new Nationality { Id=idCounter++, NationalityName = "Chadian", NationalityCode = "TCD" },
            new Nationality { Id=idCounter++, NationalityName = "Chilean", NationalityCode = "CHL" },
            new Nationality { Id=idCounter++, NationalityName = "Chinese", NationalityCode = "CHN" },
            new Nationality { Id=idCounter++, NationalityName = "Colombian", NationalityCode = "COL" },
            new Nationality { Id=idCounter++, NationalityName = "Comoran", NationalityCode = "COM" },
            new Nationality { Id=idCounter++, NationalityName = "Congolese", NationalityCode = "COG" },
            new Nationality { Id=idCounter++, NationalityName = "Costa Rican", NationalityCode = "CRI" },
            new Nationality { Id=idCounter++, NationalityName = "Croatian", NationalityCode = "HRV" },
            new Nationality { Id=idCounter++, NationalityName = "Cuban", NationalityCode = "CUB" },
            new Nationality { Id=idCounter++, NationalityName = "Cypriot", NationalityCode = "CYP" },
            new Nationality { Id=idCounter++, NationalityName = "Czech", NationalityCode = "CZE" },
            new Nationality { Id=idCounter++, NationalityName = "Danish", NationalityCode = "DNK" },
            new Nationality { Id=idCounter++, NationalityName = "Djiboutian", NationalityCode = "DJI" },
            new Nationality { Id=idCounter++, NationalityName = "Dominican", NationalityCode = "DOM" },
            new Nationality { Id=idCounter++, NationalityName = "Dutch", NationalityCode = "NLD" },
            new Nationality { Id=idCounter++, NationalityName = "East Timorese", NationalityCode = "TLS" },
            new Nationality { Id=idCounter++, NationalityName = "Ecuadorean", NationalityCode = "ECU" },
            new Nationality { Id=idCounter++, NationalityName = "Egyptian", NationalityCode = "EGY" },
            new Nationality { Id=idCounter++, NationalityName = "Emirian", NationalityCode = "ARE" },
            new Nationality { Id=idCounter++, NationalityName = "Equatorial Guinean", NationalityCode = "GNQ" },
            new Nationality { Id=idCounter++, NationalityName = "Eritrean", NationalityCode = "ERI" },
            new Nationality { Id=idCounter++, NationalityName = "Estonian", NationalityCode = "EST" },
            new Nationality { Id=idCounter++, NationalityName = "Ethiopian", NationalityCode = "ETH" },
            new Nationality { Id=idCounter++, NationalityName = "Fijian", NationalityCode = "FJI" },
            new Nationality { Id=idCounter++, NationalityName = "Filipino", NationalityCode = "PHL" },
            new Nationality { Id=idCounter++, NationalityName = "Finnish", NationalityCode = "FIN" },
            new Nationality { Id=idCounter++, NationalityName = "French", NationalityCode = "FRA" },
            new Nationality { Id=idCounter++, NationalityName = "Gabonese", NationalityCode = "GAB" },
            new Nationality { Id=idCounter++, NationalityName = "Gambian", NationalityCode = "GMB" },
            new Nationality { Id=idCounter++, NationalityName = "Georgian", NationalityCode = "GEO" },
            new Nationality { Id=idCounter++, NationalityName = "German", NationalityCode = "DEU" },
            new Nationality { Id=idCounter++, NationalityName = "Ghanaian", NationalityCode = "GHA" },
            new Nationality { Id=idCounter++, NationalityName = "Greek", NationalityCode = "GRC" },
            new Nationality { Id=idCounter++, NationalityName = "Grenadian", NationalityCode = "GRD" },
            new Nationality { Id=idCounter++, NationalityName = "Guatemalan", NationalityCode = "GTM" },
            new Nationality { Id=idCounter++, NationalityName = "Guinea-Bissauan", NationalityCode = "GNB" },
            new Nationality { Id=idCounter++, NationalityName = "Guinean", NationalityCode = "GIN" },
            new Nationality { Id=idCounter++, NationalityName = "Guyanese", NationalityCode = "GUY" },
            new Nationality { Id=idCounter++, NationalityName = "Haitian", NationalityCode = "HTI" },
            new Nationality { Id=idCounter++, NationalityName = "Herzegovinian", NationalityCode = "BIH" },
            new Nationality { Id=idCounter++, NationalityName = "Honduran", NationalityCode = "HND" },
            new Nationality { Id=idCounter++, NationalityName = "Hungarian", NationalityCode = "HUN" },
            new Nationality { Id=idCounter++, NationalityName = "I-Kiribati", NationalityCode = "KIR" },
            new Nationality { Id=idCounter++, NationalityName = "Icelander", NationalityCode = "ISL" },
            new Nationality { Id=idCounter++, NationalityName = "Indian", NationalityCode = "IND" },
            new Nationality { Id=idCounter++, NationalityName = "Indonesian", NationalityCode = "IDN" },
            new Nationality { Id=idCounter++, NationalityName = "Iranian", NationalityCode = "IRN" },
            new Nationality { Id=idCounter++, NationalityName = "Iraqi", NationalityCode = "IRQ" },
            new Nationality { Id=idCounter++, NationalityName = "Irish", NationalityCode = "IRL" },
            new Nationality { Id=idCounter++, NationalityName = "Israeli", NationalityCode = "ISR" },
            new Nationality { Id=idCounter++, NationalityName = "Italian", NationalityCode = "ITA" },
            new Nationality { Id=idCounter++, NationalityName = "Ivorian", NationalityCode = "CIV" },
            new Nationality { Id=idCounter++, NationalityName = "Jamaican", NationalityCode = "JAM" },
            new Nationality { Id=idCounter++, NationalityName = "Japanese", NationalityCode = "JPN" },
            new Nationality { Id=idCounter++, NationalityName = "Jordanian", NationalityCode = "JOR" },
            new Nationality { Id=idCounter++, NationalityName = "Kazakhstani", NationalityCode = "KAZ" },
            new Nationality { Id=idCounter++, NationalityName = "Kenyan", NationalityCode = "KEN" },
            new Nationality { Id=idCounter++, NationalityName = "Kittian and Nevisian", NationalityCode = "KNA" },
            new Nationality { Id=idCounter++, NationalityName = "Kuwaiti", NationalityCode = "KWT" },
            new Nationality { Id=idCounter++, NationalityName = "Kyrgyz", NationalityCode = "KGZ" },
            new Nationality { Id=idCounter++, NationalityName = "Laotian", NationalityCode = "LAO" },
            new Nationality { Id=idCounter++, NationalityName = "Latvian", NationalityCode = "LVA" },
            new Nationality { Id=idCounter++, NationalityName = "Lebanese", NationalityCode = "LBN" },
            new Nationality { Id=idCounter++, NationalityName = "Liberian", NationalityCode = "LBR" },
            new Nationality { Id=idCounter++, NationalityName = "Libyan", NationalityCode = "LBY" },
            new Nationality { Id=idCounter++, NationalityName = "Liechtensteiner", NationalityCode = "LIE" },
            new Nationality { Id=idCounter++, NationalityName = "Lithuanian", NationalityCode = "LTU" },
            new Nationality { Id=idCounter++, NationalityName = "Luxembourger", NationalityCode = "LUX" },
            new Nationality { Id=idCounter++, NationalityName = "Malagasy", NationalityCode = "MDG" },
            new Nationality { Id=idCounter++, NationalityName = "Malawian", NationalityCode = "MWI" },
            new Nationality { Id=idCounter++, NationalityName = "Malaysian", NationalityCode = "MYS" },
            new Nationality { Id=idCounter++, NationalityName = "Maldivan", NationalityCode = "MDV" },
            new Nationality { Id=idCounter++, NationalityName = "Malian", NationalityCode = "MLI" },
            new Nationality { Id=idCounter++, NationalityName = "Maltese", NationalityCode = "MLT" },
            new Nationality { Id=idCounter++, NationalityName = "Marshallese", NationalityCode = "MHL" },
            new Nationality { Id=idCounter++, NationalityName = "Mauritanian", NationalityCode = "MRT" },
            new Nationality { Id=idCounter++, NationalityName = "Mauritian", NationalityCode = "MUS" },
            new Nationality { Id=idCounter++, NationalityName = "Mexican", NationalityCode = "MEX" },
            new Nationality { Id=idCounter++, NationalityName = "Micronesian", NationalityCode = "FSM" },
            new Nationality { Id=idCounter++, NationalityName = "Moldovan", NationalityCode = "MDA" },
            new Nationality { Id=idCounter++, NationalityName = "Monacan", NationalityCode = "MCO" },
            new Nationality { Id=idCounter++, NationalityName = "Mongolian", NationalityCode = "MNG" },
            new Nationality { Id=idCounter++, NationalityName = "Montenegrin", NationalityCode = "MNE" },
            new Nationality { Id=idCounter++, NationalityName = "Moroccan", NationalityCode = "MAR" },
            new Nationality { Id=idCounter++, NationalityName = "Mosotho", NationalityCode = "LSO" },
            new Nationality { Id=idCounter++, NationalityName = "Motswana", NationalityCode = "BWA" },
            new Nationality { Id=idCounter++, NationalityName = "Mozambican", NationalityCode = "MOZ" },
            new Nationality { Id=idCounter++, NationalityName = "Namibian", NationalityCode = "NAM" },
            new Nationality { Id=idCounter++, NationalityName = "Nauruan", NationalityCode = "NRU" },
            new Nationality { Id=idCounter++, NationalityName = "Nepalese", NationalityCode = "NPL" },
            new Nationality { Id=idCounter++, NationalityName = "Netherlander", NationalityCode = "NLD" },
            new Nationality { Id=idCounter++, NationalityName = "New Zealander", NationalityCode = "NZL" },
            new Nationality { Id=idCounter++, NationalityName = "Nicaraguan", NationalityCode = "NIC" },
            new Nationality { Id=idCounter++, NationalityName = "Nigerian", NationalityCode = "NGA" },
            new Nationality { Id=idCounter++, NationalityName = "North Korean", NationalityCode = "PRK" },
            new Nationality { Id=idCounter++, NationalityName = "Northern Irish", NationalityCode = "GB-NIR" },
            new Nationality { Id=idCounter++, NationalityName = "Norwegian", NationalityCode = "NOR" },
            new Nationality { Id=idCounter++, NationalityName = "Omani", NationalityCode = "OMN" },
            new Nationality { Id=idCounter++, NationalityName = "Pakistani", NationalityCode = "PAK" },
            new Nationality { Id=idCounter++, NationalityName = "Palauan", NationalityCode = "PLW" },
            new Nationality { Id=idCounter++, NationalityName = "Panamanian", NationalityCode = "PAN" },
            new Nationality { Id=idCounter++, NationalityName = "Papua New Guinean", NationalityCode = "PNG" },
            new Nationality { Id=idCounter++, NationalityName = "Paraguayan", NationalityCode = "PRY" },
            new Nationality { Id=idCounter++, NationalityName = "Peruvian", NationalityCode = "PER" },
            new Nationality { Id=idCounter++, NationalityName = "Polish", NationalityCode = "POL" },
            new Nationality { Id=idCounter++, NationalityName = "Portuguese", NationalityCode = "PRT" },
            new Nationality { Id=idCounter++, NationalityName = "Qatari", NationalityCode = "QAT" },
            new Nationality { Id=idCounter++, NationalityName = "Romanian", NationalityCode = "ROU" },
            new Nationality { Id=idCounter++, NationalityName = "Russian", NationalityCode = "RUS" },
            new Nationality { Id=idCounter++, NationalityName = "Rwandan", NationalityCode = "RWA" },
            new Nationality { Id=idCounter++, NationalityName = "Saint Kitts and Nevis", NationalityCode = "KNA" },
            new Nationality { Id=idCounter++, NationalityName = "Saint Lucian", NationalityCode = "LCA" },
            new Nationality { Id=idCounter++, NationalityName = "Saint Vincent and Grenadines", NationalityCode = "VCT" },
            new Nationality { Id=idCounter++, NationalityName = "Samoan", NationalityCode = "WSM" },
            new Nationality { Id=idCounter++, NationalityName = "San Marinese", NationalityCode = "SMR" },
            new Nationality { Id=idCounter++, NationalityName = "Sao Tomean", NationalityCode = "STP" },
            new Nationality { Id=idCounter++, NationalityName = "Saudi", NationalityCode = "SAU" },
            new Nationality { Id=idCounter++, NationalityName = "Scottish", NationalityCode = "GB-SCT" },
            new Nationality { Id=idCounter++, NationalityName = "Senegalese", NationalityCode = "SEN" },
            new Nationality { Id=idCounter++, NationalityName = "Serbian", NationalityCode = "SRB" },
            new Nationality { Id=idCounter++, NationalityName = "Seychellois", NationalityCode = "SYC" },
            new Nationality { Id=idCounter++, NationalityName = "Sierra Leonean", NationalityCode = "SLE" },
            new Nationality { Id=idCounter++, NationalityName = "Singaporean", NationalityCode = "SGP" },
            new Nationality { Id=idCounter++, NationalityName = "Slovak", NationalityCode = "SVK" },
            new Nationality { Id=idCounter++, NationalityName = "Slovene", NationalityCode = "SVN" },
            new Nationality { Id=idCounter++, NationalityName = "Solomon Islander", NationalityCode = "SLB" },
            new Nationality { Id=idCounter++, NationalityName = "Somali", NationalityCode = "SOM" },
            new Nationality { Id=idCounter++, NationalityName = "South African", NationalityCode = "ZAF" },
            new Nationality { Id=idCounter++, NationalityName = "South Korean", NationalityCode = "KOR" },
            new Nationality { Id=idCounter++, NationalityName = "Spanish", NationalityCode = "ESP" },
            new Nationality { Id=idCounter++, NationalityName = "Sri Lankan", NationalityCode = "LKA" },
            new Nationality { Id=idCounter++, NationalityName = "Sudanese", NationalityCode = "SDN" },
            new Nationality { Id=idCounter++, NationalityName = "Surinamese", NationalityCode = "SUR" },
            new Nationality { Id=idCounter++, NationalityName = "Swazi", NationalityCode = "SWZ" },
            new Nationality { Id=idCounter++, NationalityName = "Swedish", NationalityCode = "SWE" },
            new Nationality { Id=idCounter++, NationalityName = "Swiss", NationalityCode = "CHE" },
            new Nationality { Id=idCounter++, NationalityName = "Syrian", NationalityCode = "SYR" },
            new Nationality { Id=idCounter++, NationalityName = "Taiwanese", NationalityCode = "TWN" },
            new Nationality { Id=idCounter++, NationalityName = "Tajik", NationalityCode = "TJK" },
            new Nationality { Id=idCounter++, NationalityName = "Tanzanian", NationalityCode = "TZA" },
            new Nationality { Id=idCounter++, NationalityName = "Thai", NationalityCode = "THA" },
            new Nationality { Id=idCounter++, NationalityName = "Togolese", NationalityCode = "TGO" },
            new Nationality { Id=idCounter++, NationalityName = "Tongan", NationalityCode = "TON" },
            new Nationality { Id=idCounter++, NationalityName = "Trinidadian or Tobagonian", NationalityCode = "TTO" },
            new Nationality { Id=idCounter++, NationalityName = "Tunisian", NationalityCode = "TUN" },
            new Nationality { Id=idCounter++, NationalityName = "Turkish", NationalityCode = "TUR" },
            new Nationality { Id=idCounter++, NationalityName = "Tuvaluan", NationalityCode = "TUV" },
            new Nationality { Id=idCounter++, NationalityName = "Ugandan", NationalityCode = "UGA" },
            new Nationality { Id=idCounter++, NationalityName = "Ukrainian", NationalityCode = "UKR" },
            new Nationality { Id=idCounter++, NationalityName = "Uruguayan", NationalityCode = "URY" },
            new Nationality { Id=idCounter++, NationalityName = "Uzbek", NationalityCode = "UZB" },
            new Nationality { Id=idCounter++, NationalityName = "Vanuatu", NationalityCode = "VUT" },
            new Nationality { Id=idCounter++, NationalityName = "Vatican", NationalityCode = "VAT" },
            new Nationality { Id=idCounter++, NationalityName = "Venezuelan", NationalityCode = "VEN" },
            new Nationality { Id=idCounter++, NationalityName = "Vietnamese", NationalityCode = "VNM" },
            new Nationality { Id=idCounter++, NationalityName = "Welsh", NationalityCode = "GB-WLS" },
            new Nationality { Id=idCounter++, NationalityName = "Yemeni", NationalityCode = "YEM" },
            new Nationality { Id=idCounter++, NationalityName = "Zambian", NationalityCode = "ZMB" },
            new Nationality { Id=idCounter++, NationalityName = "Zimbabwean", NationalityCode = "ZWE" },
        };
    }
}
