// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyVault.WebApi.Backend.Models;

#nullable disable

namespace SkyVault.WebApi.Migrations
{
    [DbContext(typeof(SkyvaultContext))]
    [Migration("20240320125955_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.CommunicationMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CommTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comm_title");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("communication_methods", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.CustomerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int>("PreferredCommId")
                        .HasColumnType("int")
                        .HasColumnName("preferred_comm_id");

                    b.Property<int>("SalutationId")
                        .HasColumnType("int")
                        .HasColumnName("salutation_id");

                    b.Property<int>("SystemUserId")
                        .HasColumnType("int")
                        .HasColumnName("system_user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PreferredCommId" }, "fk_customerprofiles_communication_methods");

                    b.HasIndex(new[] { "ParentId" }, "fk_customerprofiles_customerprofiles");

                    b.HasIndex(new[] { "SalutationId" }, "fk_customerprofiles_salutations");

                    b.HasIndex(new[] { "SystemUserId" }, "fk_customerprofiles_system_users");

                    b.ToTable("customer_profiles", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.FrequentFlyerNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int")
                        .HasColumnName("customer_profile_id");

                    b.Property<string>("FlyerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("flyer_number");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerProfileId" }, "fk_frequentflyernumbers_customerprofiles");

                    b.ToTable("frequent_flyer_numbers", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int")
                        .HasColumnName("customer_profile_id");

                    b.Property<DateOnly>("DateTime")
                        .HasColumnType("date")
                        .HasColumnName("date_time");

                    b.Property<string>("Log")
                        .HasColumnType("text")
                        .HasColumnName("log");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("status")
                        .IsFixedLength();

                    b.Property<int>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerProfileId" }, "fk_jobs_customerprofiles");

                    b.HasIndex(new[] { "TemplateId" }, "fk_jobs_notification_templates");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("NationalityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nationality_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("nationalities", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<string>("File")
                        .HasColumnType("longtext")
                        .HasColumnName("file");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int")
                        .HasColumnName("notification_type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NotificationType" }, "fk_notification_templates_notification_types");

                    b.ToTable("notification_templates", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("notification_types", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Passport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int")
                        .HasColumnName("customer_profile_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("gender");

                    b.Property<string>("IsPrimary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("is_primary")
                        .HasDefaultValueSql("'0'")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int")
                        .HasColumnName("nationality_id");

                    b.Property<string>("OtherNames")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("other_names");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("passport_number");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("place_of_birth");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerProfileId" }, "fk_passports_customerprofiles");

                    b.HasIndex(new[] { "NationalityId" }, "fk_passports_nationalities");

                    b.ToTable("passports", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Salutation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("SalutationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("salutation_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("salutations", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'")
                        .IsFixedLength();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture");

                    b.Property<string>("SamProfileId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sam_profile_id");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("user_role");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("system_users", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Visa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateOnly>("ExpireDate")
                        .HasColumnType("date")
                        .HasColumnName("expire_date");

                    b.Property<DateOnly>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<string>("IssuedPlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("issued_place");

                    b.Property<int>("PassportId")
                        .HasColumnType("int")
                        .HasColumnName("passport_id");

                    b.Property<string>("VisaNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("visa_number");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CountryId" }, "fk_visas_countries");

                    b.HasIndex(new[] { "PassportId" }, "fk_visas_passports");

                    b.ToTable("visas", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.CustomerProfile", b =>
                {
                    b.HasOne("SkyVault.WebApi.Backend.Models.CustomerProfile", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_customerprofiles_customerprofiles");

                    b.HasOne("SkyVault.WebApi.Backend.Models.CommunicationMethod", "PreferredComm")
                        .WithMany("CustomerProfiles")
                        .HasForeignKey("PreferredCommId")
                        .IsRequired()
                        .HasConstraintName("fk_customerprofiles_communication_methods");

                    b.HasOne("SkyVault.WebApi.Backend.Models.Salutation", "Salutation")
                        .WithMany("CustomerProfiles")
                        .HasForeignKey("SalutationId")
                        .IsRequired()
                        .HasConstraintName("fk_customerprofiles_salutations");

                    b.HasOne("SkyVault.WebApi.Backend.Models.SystemUser", "SystemUser")
                        .WithMany("CustomerProfiles")
                        .HasForeignKey("SystemUserId")
                        .IsRequired()
                        .HasConstraintName("fk_customerprofiles_system_users");

                    b.Navigation("Parent");

                    b.Navigation("PreferredComm");

                    b.Navigation("Salutation");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.FrequentFlyerNumber", b =>
                {
                    b.HasOne("SkyVault.WebApi.Backend.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("FrequentFlyerNumbers")
                        .HasForeignKey("CustomerProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_frequentflyernumbers_customerprofiles");

                    b.Navigation("CustomerProfile");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Job", b =>
                {
                    b.HasOne("SkyVault.WebApi.Backend.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("Jobs")
                        .HasForeignKey("CustomerProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_jobs_customerprofiles");

                    b.HasOne("SkyVault.WebApi.Backend.Models.NotificationTemplate", "Template")
                        .WithMany("Jobs")
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("fk_jobs_notification_templates");

                    b.Navigation("CustomerProfile");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.NotificationTemplate", b =>
                {
                    b.HasOne("SkyVault.WebApi.Backend.Models.NotificationType", "NotificationTypeNavigation")
                        .WithMany("NotificationTemplates")
                        .HasForeignKey("NotificationType")
                        .IsRequired()
                        .HasConstraintName("fk_notification_templates_notification_types");

                    b.Navigation("NotificationTypeNavigation");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Passport", b =>
                {
                    b.HasOne("SkyVault.WebApi.Backend.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("Passports")
                        .HasForeignKey("CustomerProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_passports_customerprofiles");

                    b.HasOne("SkyVault.WebApi.Backend.Models.Nationality", "Nationality")
                        .WithMany("Passports")
                        .HasForeignKey("NationalityId")
                        .IsRequired()
                        .HasConstraintName("fk_passports_nationalities");

                    b.Navigation("CustomerProfile");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Visa", b =>
                {
                    b.HasOne("SkyVault.WebApi.Backend.Models.Country", "Country")
                        .WithMany("Visas")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("fk_visas_countries");

                    b.HasOne("SkyVault.WebApi.Backend.Models.Passport", "Passport")
                        .WithMany("Visas")
                        .HasForeignKey("PassportId")
                        .IsRequired()
                        .HasConstraintName("fk_visas_passports");

                    b.Navigation("Country");

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.CommunicationMethod", b =>
                {
                    b.Navigation("CustomerProfiles");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Country", b =>
                {
                    b.Navigation("Visas");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.CustomerProfile", b =>
                {
                    b.Navigation("FrequentFlyerNumbers");

                    b.Navigation("InverseParent");

                    b.Navigation("Jobs");

                    b.Navigation("Passports");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Nationality", b =>
                {
                    b.Navigation("Passports");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.NotificationTemplate", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.NotificationType", b =>
                {
                    b.Navigation("NotificationTemplates");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Passport", b =>
                {
                    b.Navigation("Visas");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Salutation", b =>
                {
                    b.Navigation("CustomerProfiles");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.SystemUser", b =>
                {
                    b.Navigation("CustomerProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
