// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyVault.WebApi.Backend.Models;

#nullable disable

namespace SkyVault.WebApi.Migrations
{
    [DbContext(typeof(SkyvaultContext))]
    [Migration("20240324151801_AddingSeedData")]
    partial class AddingSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.CommunicationMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CommTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comm_title");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("communication_methods", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            CountryName = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            CountryName = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            CountryName = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            CountryName = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            CountryName = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            CountryName = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            CountryName = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            CountryName = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            CountryName = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            CountryName = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            CountryName = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            CountryName = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            CountryName = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            CountryName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            CountryName = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            CountryName = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            CountryName = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            CountryName = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            CountryName = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            CountryName = "Cabo Verde"
                        },
                        new
                        {
                            Id = 30,
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            Id = 31,
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            Id = 32,
                            CountryName = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            CountryName = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            CountryName = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            CountryName = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            CountryName = "China"
                        },
                        new
                        {
                            Id = 37,
                            CountryName = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            CountryName = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            CountryName = "Congo (Congo-Brazzaville)"
                        },
                        new
                        {
                            Id = 40,
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            Id = 41,
                            CountryName = "Croatia"
                        },
                        new
                        {
                            Id = 42,
                            CountryName = "Cuba"
                        },
                        new
                        {
                            Id = 43,
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            Id = 44,
                            CountryName = "Czechia (Czech Republic)"
                        },
                        new
                        {
                            Id = 45,
                            CountryName = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = 46,
                            CountryName = "Denmark"
                        },
                        new
                        {
                            Id = 47,
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            Id = 48,
                            CountryName = "Dominica"
                        },
                        new
                        {
                            Id = 49,
                            CountryName = "Dominican Republic"
                        },
                        new
                        {
                            Id = 50,
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            Id = 51,
                            CountryName = "Egypt"
                        },
                        new
                        {
                            Id = 52,
                            CountryName = "El Salvador"
                        },
                        new
                        {
                            Id = 53,
                            CountryName = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 54,
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            Id = 55,
                            CountryName = "Estonia"
                        },
                        new
                        {
                            Id = 56,
                            CountryName = "Swaziland"
                        },
                        new
                        {
                            Id = 57,
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            Id = 58,
                            CountryName = "Fiji"
                        },
                        new
                        {
                            Id = 59,
                            CountryName = "Finland"
                        },
                        new
                        {
                            Id = 60,
                            CountryName = "France"
                        },
                        new
                        {
                            Id = 61,
                            CountryName = "Gabon"
                        },
                        new
                        {
                            Id = 62,
                            CountryName = "Gambia"
                        },
                        new
                        {
                            Id = 63,
                            CountryName = "Georgia"
                        },
                        new
                        {
                            Id = 64,
                            CountryName = "Germany"
                        },
                        new
                        {
                            Id = 65,
                            CountryName = "Ghana"
                        },
                        new
                        {
                            Id = 66,
                            CountryName = "Greece"
                        },
                        new
                        {
                            Id = 67,
                            CountryName = "Grenada"
                        },
                        new
                        {
                            Id = 68,
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            Id = 69,
                            CountryName = "Guinea"
                        },
                        new
                        {
                            Id = 70,
                            CountryName = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 71,
                            CountryName = "Guyana"
                        },
                        new
                        {
                            Id = 72,
                            CountryName = "Haiti"
                        },
                        new
                        {
                            Id = 73,
                            CountryName = "Holy See"
                        },
                        new
                        {
                            Id = 74,
                            CountryName = "Honduras"
                        },
                        new
                        {
                            Id = 75,
                            CountryName = "Hungary"
                        },
                        new
                        {
                            Id = 76,
                            CountryName = "Iceland"
                        },
                        new
                        {
                            Id = 77,
                            CountryName = "India"
                        },
                        new
                        {
                            Id = 78,
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            Id = 79,
                            CountryName = "Iran"
                        },
                        new
                        {
                            Id = 80,
                            CountryName = "Iraq"
                        },
                        new
                        {
                            Id = 81,
                            CountryName = "Ireland"
                        },
                        new
                        {
                            Id = 82,
                            CountryName = "Israel"
                        },
                        new
                        {
                            Id = 83,
                            CountryName = "Italy"
                        },
                        new
                        {
                            Id = 84,
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            Id = 85,
                            CountryName = "Japan"
                        },
                        new
                        {
                            Id = 86,
                            CountryName = "Jordan"
                        },
                        new
                        {
                            Id = 87,
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            Id = 88,
                            CountryName = "Kenya"
                        },
                        new
                        {
                            Id = 89,
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            Id = 90,
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            Id = 91,
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 92,
                            CountryName = "Laos"
                        },
                        new
                        {
                            Id = 93,
                            CountryName = "Latvia"
                        },
                        new
                        {
                            Id = 94,
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            Id = 95,
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            Id = 96,
                            CountryName = "Liberia"
                        },
                        new
                        {
                            Id = 97,
                            CountryName = "Libya"
                        },
                        new
                        {
                            Id = 98,
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            Id = 99,
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            Id = 100,
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            Id = 101,
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            Id = 102,
                            CountryName = "Malawi"
                        },
                        new
                        {
                            Id = 103,
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            Id = 104,
                            CountryName = "Maldives"
                        },
                        new
                        {
                            Id = 105,
                            CountryName = "Mali"
                        },
                        new
                        {
                            Id = 106,
                            CountryName = "Malta"
                        },
                        new
                        {
                            Id = 107,
                            CountryName = "Marshall Islands"
                        },
                        new
                        {
                            Id = 108,
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            Id = 109,
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            Id = 110,
                            CountryName = "Mexico"
                        },
                        new
                        {
                            Id = 111,
                            CountryName = "Micronesia"
                        },
                        new
                        {
                            Id = 112,
                            CountryName = "Moldova"
                        },
                        new
                        {
                            Id = 113,
                            CountryName = "Monaco"
                        },
                        new
                        {
                            Id = 114,
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            Id = 115,
                            CountryName = "Montenegro"
                        },
                        new
                        {
                            Id = 116,
                            CountryName = "Morocco"
                        },
                        new
                        {
                            Id = 117,
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            Id = 118,
                            CountryName = "Myanmar"
                        },
                        new
                        {
                            Id = 119,
                            CountryName = "Namibia"
                        },
                        new
                        {
                            Id = 120,
                            CountryName = "Nauru"
                        },
                        new
                        {
                            Id = 121,
                            CountryName = "Nepal"
                        },
                        new
                        {
                            Id = 122,
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            Id = 123,
                            CountryName = "New Zealand"
                        },
                        new
                        {
                            Id = 124,
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            Id = 125,
                            CountryName = "Niger"
                        },
                        new
                        {
                            Id = 126,
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            Id = 127,
                            CountryName = "North Korea"
                        },
                        new
                        {
                            Id = 128,
                            CountryName = "North Macedonia"
                        },
                        new
                        {
                            Id = 129,
                            CountryName = "Norway"
                        },
                        new
                        {
                            Id = 130,
                            CountryName = "Oman"
                        },
                        new
                        {
                            Id = 131,
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            Id = 132,
                            CountryName = "Palau"
                        },
                        new
                        {
                            Id = 133,
                            CountryName = "Palestine State"
                        },
                        new
                        {
                            Id = 134,
                            CountryName = "Panama"
                        },
                        new
                        {
                            Id = 135,
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 136,
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            Id = 137,
                            CountryName = "Peru"
                        },
                        new
                        {
                            Id = 138,
                            CountryName = "Philippines"
                        },
                        new
                        {
                            Id = 139,
                            CountryName = "Poland"
                        },
                        new
                        {
                            Id = 140,
                            CountryName = "Portugal"
                        },
                        new
                        {
                            Id = 141,
                            CountryName = "Qatar"
                        },
                        new
                        {
                            Id = 142,
                            CountryName = "Romania"
                        },
                        new
                        {
                            Id = 143,
                            CountryName = "Russia"
                        },
                        new
                        {
                            Id = 144,
                            CountryName = "Rwanda"
                        },
                        new
                        {
                            Id = 145,
                            CountryName = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 146,
                            CountryName = "Saint Lucia"
                        },
                        new
                        {
                            Id = 147,
                            CountryName = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 148,
                            CountryName = "Samoa"
                        },
                        new
                        {
                            Id = 149,
                            CountryName = "San Marino"
                        },
                        new
                        {
                            Id = 150,
                            CountryName = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 151,
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 152,
                            CountryName = "Senegal"
                        },
                        new
                        {
                            Id = 153,
                            CountryName = "Serbia"
                        },
                        new
                        {
                            Id = 154,
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            Id = 155,
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            Id = 156,
                            CountryName = "Singapore"
                        },
                        new
                        {
                            Id = 157,
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            Id = 158,
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            Id = 159,
                            CountryName = "Solomon Islands"
                        },
                        new
                        {
                            Id = 160,
                            CountryName = "Somalia"
                        },
                        new
                        {
                            Id = 161,
                            CountryName = "South Africa"
                        },
                        new
                        {
                            Id = 162,
                            CountryName = "South Korea"
                        },
                        new
                        {
                            Id = 163,
                            CountryName = "South Sudan"
                        },
                        new
                        {
                            Id = 164,
                            CountryName = "Spain"
                        },
                        new
                        {
                            Id = 165,
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            Id = 166,
                            CountryName = "Sudan"
                        },
                        new
                        {
                            Id = 167,
                            CountryName = "Suriname"
                        },
                        new
                        {
                            Id = 168,
                            CountryName = "Sweden"
                        },
                        new
                        {
                            Id = 169,
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            Id = 170,
                            CountryName = "Syria"
                        },
                        new
                        {
                            Id = 171,
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            Id = 172,
                            CountryName = "Tanzania"
                        },
                        new
                        {
                            Id = 173,
                            CountryName = "Thailand"
                        },
                        new
                        {
                            Id = 174,
                            CountryName = "Timor-Leste"
                        },
                        new
                        {
                            Id = 175,
                            CountryName = "Togo"
                        },
                        new
                        {
                            Id = 176,
                            CountryName = "Tonga"
                        },
                        new
                        {
                            Id = 177,
                            CountryName = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 178,
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            Id = 179,
                            CountryName = "Turkey"
                        },
                        new
                        {
                            Id = 180,
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            Id = 181,
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            Id = 182,
                            CountryName = "Uganda"
                        },
                        new
                        {
                            Id = 183,
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            Id = 184,
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 185,
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            Id = 186,
                            CountryName = "United States of America"
                        },
                        new
                        {
                            Id = 187,
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            Id = 188,
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            Id = 189,
                            CountryName = "Vanuatu"
                        },
                        new
                        {
                            Id = 190,
                            CountryName = "Venezuela"
                        },
                        new
                        {
                            Id = 191,
                            CountryName = "Vietnam"
                        },
                        new
                        {
                            Id = 192,
                            CountryName = "Yemen"
                        },
                        new
                        {
                            Id = 193,
                            CountryName = "Zambia"
                        },
                        new
                        {
                            Id = 194,
                            CountryName = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.CustomerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int>("PreferredCommId")
                        .HasColumnType("int")
                        .HasColumnName("preferred_comm_id");

                    b.Property<int>("SalutationId")
                        .HasColumnType("int")
                        .HasColumnName("salutation_id");

                    b.Property<int>("SystemUserId")
                        .HasColumnType("int")
                        .HasColumnName("system_user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PreferredCommId" }, "fk_customerprofiles_communication_methods");

                    b.HasIndex(new[] { "ParentId" }, "fk_customerprofiles_customerprofiles");

                    b.HasIndex(new[] { "SalutationId" }, "fk_customerprofiles_salutations");

                    b.HasIndex(new[] { "SystemUserId" }, "fk_customerprofiles_system_users");

                    b.ToTable("customer_profiles", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.FrequentFlyerNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int")
                        .HasColumnName("customer_profile_id");

                    b.Property<string>("FlyerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("flyer_number");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerProfileId" }, "fk_frequentflyernumbers_customerprofiles");

                    b.ToTable("frequent_flyer_numbers", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int")
                        .HasColumnName("customer_profile_id");

                    b.Property<DateOnly>("DateTime")
                        .HasColumnType("date")
                        .HasColumnName("date_time");

                    b.Property<string>("Log")
                        .HasColumnType("text")
                        .HasColumnName("log");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("status")
                        .IsFixedLength();

                    b.Property<int>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerProfileId" }, "fk_jobs_customerprofiles");

                    b.HasIndex(new[] { "TemplateId" }, "fk_jobs_notification_templates");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("NationalityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nationality_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("nationalities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NationalityName = "Afghan"
                        },
                        new
                        {
                            Id = 2,
                            NationalityName = "Albanian"
                        },
                        new
                        {
                            Id = 3,
                            NationalityName = "Algerian"
                        },
                        new
                        {
                            Id = 4,
                            NationalityName = "American"
                        },
                        new
                        {
                            Id = 5,
                            NationalityName = "Andorran"
                        },
                        new
                        {
                            Id = 6,
                            NationalityName = "Angolan"
                        },
                        new
                        {
                            Id = 7,
                            NationalityName = "Antiguans"
                        },
                        new
                        {
                            Id = 8,
                            NationalityName = "Argentinean"
                        },
                        new
                        {
                            Id = 9,
                            NationalityName = "Armenian"
                        },
                        new
                        {
                            Id = 10,
                            NationalityName = "Australian"
                        },
                        new
                        {
                            Id = 11,
                            NationalityName = "Austrian"
                        },
                        new
                        {
                            Id = 12,
                            NationalityName = "Azerbaijani"
                        },
                        new
                        {
                            Id = 13,
                            NationalityName = "Bahamian"
                        },
                        new
                        {
                            Id = 14,
                            NationalityName = "Bahraini"
                        },
                        new
                        {
                            Id = 15,
                            NationalityName = "Bangladeshi"
                        },
                        new
                        {
                            Id = 16,
                            NationalityName = "Barbadian"
                        },
                        new
                        {
                            Id = 17,
                            NationalityName = "Belarusian"
                        },
                        new
                        {
                            Id = 18,
                            NationalityName = "Belgian"
                        },
                        new
                        {
                            Id = 19,
                            NationalityName = "Belizean"
                        },
                        new
                        {
                            Id = 20,
                            NationalityName = "Beninese"
                        },
                        new
                        {
                            Id = 21,
                            NationalityName = "Bhutanese"
                        },
                        new
                        {
                            Id = 22,
                            NationalityName = "Bolivian"
                        },
                        new
                        {
                            Id = 23,
                            NationalityName = "Bosnian"
                        },
                        new
                        {
                            Id = 24,
                            NationalityName = "Botswanan"
                        },
                        new
                        {
                            Id = 25,
                            NationalityName = "Brazilian"
                        },
                        new
                        {
                            Id = 26,
                            NationalityName = "British"
                        },
                        new
                        {
                            Id = 27,
                            NationalityName = "Bruneian"
                        },
                        new
                        {
                            Id = 28,
                            NationalityName = "Bulgarian"
                        },
                        new
                        {
                            Id = 29,
                            NationalityName = "Burkinabe"
                        },
                        new
                        {
                            Id = 30,
                            NationalityName = "Burundian"
                        },
                        new
                        {
                            Id = 31,
                            NationalityName = "Cambodian"
                        },
                        new
                        {
                            Id = 32,
                            NationalityName = "Cameroonian"
                        },
                        new
                        {
                            Id = 33,
                            NationalityName = "Canadian"
                        },
                        new
                        {
                            Id = 34,
                            NationalityName = "Cape Verdean"
                        },
                        new
                        {
                            Id = 35,
                            NationalityName = "Central African"
                        },
                        new
                        {
                            Id = 36,
                            NationalityName = "Chadian"
                        },
                        new
                        {
                            Id = 37,
                            NationalityName = "Chilean"
                        },
                        new
                        {
                            Id = 38,
                            NationalityName = "Chinese"
                        },
                        new
                        {
                            Id = 39,
                            NationalityName = "Colombian"
                        },
                        new
                        {
                            Id = 40,
                            NationalityName = "Comoran"
                        },
                        new
                        {
                            Id = 41,
                            NationalityName = "Congolese"
                        },
                        new
                        {
                            Id = 42,
                            NationalityName = "Costa Rican"
                        },
                        new
                        {
                            Id = 43,
                            NationalityName = "Croatian"
                        },
                        new
                        {
                            Id = 44,
                            NationalityName = "Cuban"
                        },
                        new
                        {
                            Id = 45,
                            NationalityName = "Cypriot"
                        },
                        new
                        {
                            Id = 46,
                            NationalityName = "Czech"
                        },
                        new
                        {
                            Id = 47,
                            NationalityName = "Danish"
                        },
                        new
                        {
                            Id = 48,
                            NationalityName = "Djiboutian"
                        },
                        new
                        {
                            Id = 49,
                            NationalityName = "Dominican"
                        },
                        new
                        {
                            Id = 50,
                            NationalityName = "Dutch"
                        },
                        new
                        {
                            Id = 51,
                            NationalityName = "East Timorese"
                        },
                        new
                        {
                            Id = 52,
                            NationalityName = "Ecuadorean"
                        },
                        new
                        {
                            Id = 53,
                            NationalityName = "Egyptian"
                        },
                        new
                        {
                            Id = 54,
                            NationalityName = "Emirian"
                        },
                        new
                        {
                            Id = 55,
                            NationalityName = "Equatorial Guinean"
                        },
                        new
                        {
                            Id = 56,
                            NationalityName = "Eritrean"
                        },
                        new
                        {
                            Id = 57,
                            NationalityName = "Estonian"
                        },
                        new
                        {
                            Id = 58,
                            NationalityName = "Ethiopian"
                        },
                        new
                        {
                            Id = 59,
                            NationalityName = "Fijian"
                        },
                        new
                        {
                            Id = 60,
                            NationalityName = "Filipino"
                        },
                        new
                        {
                            Id = 61,
                            NationalityName = "Finnish"
                        },
                        new
                        {
                            Id = 62,
                            NationalityName = "French"
                        },
                        new
                        {
                            Id = 63,
                            NationalityName = "Gabonese"
                        },
                        new
                        {
                            Id = 64,
                            NationalityName = "Gambian"
                        },
                        new
                        {
                            Id = 65,
                            NationalityName = "Georgian"
                        },
                        new
                        {
                            Id = 66,
                            NationalityName = "German"
                        },
                        new
                        {
                            Id = 67,
                            NationalityName = "Ghanaian"
                        },
                        new
                        {
                            Id = 68,
                            NationalityName = "Greek"
                        },
                        new
                        {
                            Id = 69,
                            NationalityName = "Grenadian"
                        },
                        new
                        {
                            Id = 70,
                            NationalityName = "Guatemalan"
                        },
                        new
                        {
                            Id = 71,
                            NationalityName = "Guinea-Bissauan"
                        },
                        new
                        {
                            Id = 72,
                            NationalityName = "Guinean"
                        },
                        new
                        {
                            Id = 73,
                            NationalityName = "Guyanese"
                        },
                        new
                        {
                            Id = 74,
                            NationalityName = "Haitian"
                        },
                        new
                        {
                            Id = 75,
                            NationalityName = "Herzegovinian"
                        },
                        new
                        {
                            Id = 76,
                            NationalityName = "Honduran"
                        },
                        new
                        {
                            Id = 77,
                            NationalityName = "Hungarian"
                        },
                        new
                        {
                            Id = 78,
                            NationalityName = "I-Kiribati"
                        },
                        new
                        {
                            Id = 79,
                            NationalityName = "Icelander"
                        },
                        new
                        {
                            Id = 80,
                            NationalityName = "Indian"
                        },
                        new
                        {
                            Id = 81,
                            NationalityName = "Indonesian"
                        },
                        new
                        {
                            Id = 82,
                            NationalityName = "Iranian"
                        },
                        new
                        {
                            Id = 83,
                            NationalityName = "Iraqi"
                        },
                        new
                        {
                            Id = 84,
                            NationalityName = "Irish"
                        },
                        new
                        {
                            Id = 85,
                            NationalityName = "Israeli"
                        },
                        new
                        {
                            Id = 86,
                            NationalityName = "Italian"
                        },
                        new
                        {
                            Id = 87,
                            NationalityName = "Ivorian"
                        },
                        new
                        {
                            Id = 88,
                            NationalityName = "Jamaican"
                        },
                        new
                        {
                            Id = 89,
                            NationalityName = "Japanese"
                        },
                        new
                        {
                            Id = 90,
                            NationalityName = "Jordanian"
                        },
                        new
                        {
                            Id = 91,
                            NationalityName = "Kazakhstani"
                        },
                        new
                        {
                            Id = 92,
                            NationalityName = "Kenyan"
                        },
                        new
                        {
                            Id = 93,
                            NationalityName = "Kittian and Nevisian"
                        },
                        new
                        {
                            Id = 94,
                            NationalityName = "Kuwaiti"
                        },
                        new
                        {
                            Id = 95,
                            NationalityName = "Kyrgyz"
                        },
                        new
                        {
                            Id = 96,
                            NationalityName = "Laotian"
                        },
                        new
                        {
                            Id = 97,
                            NationalityName = "Latvian"
                        },
                        new
                        {
                            Id = 98,
                            NationalityName = "Lebanese"
                        },
                        new
                        {
                            Id = 99,
                            NationalityName = "Liberian"
                        },
                        new
                        {
                            Id = 100,
                            NationalityName = "Libyan"
                        },
                        new
                        {
                            Id = 101,
                            NationalityName = "Liechtensteiner"
                        },
                        new
                        {
                            Id = 102,
                            NationalityName = "Lithuanian"
                        },
                        new
                        {
                            Id = 103,
                            NationalityName = "Luxembourger"
                        },
                        new
                        {
                            Id = 104,
                            NationalityName = "Malagasy"
                        },
                        new
                        {
                            Id = 105,
                            NationalityName = "Malawian"
                        },
                        new
                        {
                            Id = 106,
                            NationalityName = "Malaysian"
                        },
                        new
                        {
                            Id = 107,
                            NationalityName = "Maldivan"
                        },
                        new
                        {
                            Id = 108,
                            NationalityName = "Malian"
                        },
                        new
                        {
                            Id = 109,
                            NationalityName = "Maltese"
                        },
                        new
                        {
                            Id = 110,
                            NationalityName = "Marshallese"
                        },
                        new
                        {
                            Id = 111,
                            NationalityName = "Mauritanian"
                        },
                        new
                        {
                            Id = 112,
                            NationalityName = "Mauritian"
                        },
                        new
                        {
                            Id = 113,
                            NationalityName = "Mexican"
                        },
                        new
                        {
                            Id = 114,
                            NationalityName = "Micronesian"
                        },
                        new
                        {
                            Id = 115,
                            NationalityName = "Moldovan"
                        },
                        new
                        {
                            Id = 116,
                            NationalityName = "Monacan"
                        },
                        new
                        {
                            Id = 117,
                            NationalityName = "Mongolian"
                        },
                        new
                        {
                            Id = 118,
                            NationalityName = "Montenegrin"
                        },
                        new
                        {
                            Id = 119,
                            NationalityName = "Moroccan"
                        },
                        new
                        {
                            Id = 120,
                            NationalityName = "Mosotho"
                        },
                        new
                        {
                            Id = 121,
                            NationalityName = "Motswana"
                        },
                        new
                        {
                            Id = 122,
                            NationalityName = "Mozambican"
                        },
                        new
                        {
                            Id = 123,
                            NationalityName = "Namibian"
                        },
                        new
                        {
                            Id = 124,
                            NationalityName = "Nauruan"
                        },
                        new
                        {
                            Id = 125,
                            NationalityName = "Nepalese"
                        },
                        new
                        {
                            Id = 126,
                            NationalityName = "Netherlander"
                        },
                        new
                        {
                            Id = 127,
                            NationalityName = "New Zealander"
                        },
                        new
                        {
                            Id = 128,
                            NationalityName = "Nicaraguan"
                        },
                        new
                        {
                            Id = 129,
                            NationalityName = "Nigerian"
                        },
                        new
                        {
                            Id = 130,
                            NationalityName = "North Korean"
                        },
                        new
                        {
                            Id = 131,
                            NationalityName = "Northern Irish"
                        },
                        new
                        {
                            Id = 132,
                            NationalityName = "Norwegian"
                        },
                        new
                        {
                            Id = 133,
                            NationalityName = "Omani"
                        },
                        new
                        {
                            Id = 134,
                            NationalityName = "Pakistani"
                        },
                        new
                        {
                            Id = 135,
                            NationalityName = "Palauan"
                        },
                        new
                        {
                            Id = 136,
                            NationalityName = "Panamanian"
                        },
                        new
                        {
                            Id = 137,
                            NationalityName = "Papua New Guinean"
                        },
                        new
                        {
                            Id = 138,
                            NationalityName = "Paraguayan"
                        },
                        new
                        {
                            Id = 139,
                            NationalityName = "Peruvian"
                        },
                        new
                        {
                            Id = 140,
                            NationalityName = "Polish"
                        },
                        new
                        {
                            Id = 141,
                            NationalityName = "Portuguese"
                        },
                        new
                        {
                            Id = 142,
                            NationalityName = "Qatari"
                        },
                        new
                        {
                            Id = 143,
                            NationalityName = "Romanian"
                        },
                        new
                        {
                            Id = 144,
                            NationalityName = "Russian"
                        },
                        new
                        {
                            Id = 145,
                            NationalityName = "Rwandan"
                        },
                        new
                        {
                            Id = 146,
                            NationalityName = "Saint Lucian"
                        },
                        new
                        {
                            Id = 147,
                            NationalityName = "Salvadoran"
                        },
                        new
                        {
                            Id = 148,
                            NationalityName = "Samoan"
                        },
                        new
                        {
                            Id = 149,
                            NationalityName = "San Marinese"
                        },
                        new
                        {
                            Id = 150,
                            NationalityName = "Sao Tomean"
                        },
                        new
                        {
                            Id = 151,
                            NationalityName = "Saudi"
                        },
                        new
                        {
                            Id = 152,
                            NationalityName = "Scottish"
                        },
                        new
                        {
                            Id = 153,
                            NationalityName = "Senegalese"
                        },
                        new
                        {
                            Id = 154,
                            NationalityName = "Serbian"
                        },
                        new
                        {
                            Id = 155,
                            NationalityName = "Seychellois"
                        },
                        new
                        {
                            Id = 156,
                            NationalityName = "Sierra Leonean"
                        },
                        new
                        {
                            Id = 157,
                            NationalityName = "Singaporean"
                        },
                        new
                        {
                            Id = 158,
                            NationalityName = "Slovak"
                        },
                        new
                        {
                            Id = 159,
                            NationalityName = "Slovenian"
                        },
                        new
                        {
                            Id = 160,
                            NationalityName = "Solomon Islander"
                        },
                        new
                        {
                            Id = 161,
                            NationalityName = "Somali"
                        },
                        new
                        {
                            Id = 162,
                            NationalityName = "South African"
                        },
                        new
                        {
                            Id = 163,
                            NationalityName = "South Korean"
                        },
                        new
                        {
                            Id = 164,
                            NationalityName = "South Sudanese"
                        },
                        new
                        {
                            Id = 165,
                            NationalityName = "Spanish"
                        },
                        new
                        {
                            Id = 166,
                            NationalityName = "Sri Lankan"
                        },
                        new
                        {
                            Id = 167,
                            NationalityName = "Sudanese"
                        },
                        new
                        {
                            Id = 168,
                            NationalityName = "Surinamer"
                        },
                        new
                        {
                            Id = 169,
                            NationalityName = "Swazi"
                        },
                        new
                        {
                            Id = 170,
                            NationalityName = "Swedish"
                        },
                        new
                        {
                            Id = 171,
                            NationalityName = "Swiss"
                        },
                        new
                        {
                            Id = 172,
                            NationalityName = "Syrian"
                        },
                        new
                        {
                            Id = 173,
                            NationalityName = "Taiwanese"
                        },
                        new
                        {
                            Id = 174,
                            NationalityName = "Tajik"
                        },
                        new
                        {
                            Id = 175,
                            NationalityName = "Tanzanian"
                        },
                        new
                        {
                            Id = 176,
                            NationalityName = "Thai"
                        },
                        new
                        {
                            Id = 177,
                            NationalityName = "Togolese"
                        },
                        new
                        {
                            Id = 178,
                            NationalityName = "Tongan"
                        },
                        new
                        {
                            Id = 179,
                            NationalityName = "Trinidadian or Tobagonian"
                        },
                        new
                        {
                            Id = 180,
                            NationalityName = "Tunisian"
                        },
                        new
                        {
                            Id = 181,
                            NationalityName = "Turkish"
                        },
                        new
                        {
                            Id = 182,
                            NationalityName = "Turkmen"
                        },
                        new
                        {
                            Id = 183,
                            NationalityName = "Tuvaluan"
                        },
                        new
                        {
                            Id = 184,
                            NationalityName = "Ugandan"
                        },
                        new
                        {
                            Id = 185,
                            NationalityName = "Ukrainian"
                        },
                        new
                        {
                            Id = 186,
                            NationalityName = "Uruguayan"
                        },
                        new
                        {
                            Id = 187,
                            NationalityName = "Uzbekistani"
                        },
                        new
                        {
                            Id = 188,
                            NationalityName = "Vanuatuan"
                        },
                        new
                        {
                            Id = 189,
                            NationalityName = "Venezuelan"
                        },
                        new
                        {
                            Id = 190,
                            NationalityName = "Vietnamese"
                        },
                        new
                        {
                            Id = 191,
                            NationalityName = "Yemeni"
                        },
                        new
                        {
                            Id = 192,
                            NationalityName = "Zambian"
                        },
                        new
                        {
                            Id = 193,
                            NationalityName = "Zimbabwean"
                        });
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<string>("File")
                        .HasColumnType("longtext")
                        .HasColumnName("file");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int")
                        .HasColumnName("notification_type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NotificationType" }, "fk_notification_templates_notification_types");

                    b.ToTable("notification_templates", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("notification_types", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Passport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int")
                        .HasColumnName("customer_profile_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("gender");

                    b.Property<string>("IsPrimary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("is_primary")
                        .HasDefaultValueSql("'0'")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int")
                        .HasColumnName("nationality_id");

                    b.Property<string>("OtherNames")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("other_names");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("passport_number");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("place_of_birth");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerProfileId" }, "fk_passports_customerprofiles");

                    b.HasIndex(new[] { "NationalityId" }, "fk_passports_nationalities");

                    b.ToTable("passports", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Salutation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("SalutationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("salutation_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("salutations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SalutationName = "Mr"
                        },
                        new
                        {
                            Id = 2,
                            SalutationName = "Mrs"
                        },
                        new
                        {
                            Id = 3,
                            SalutationName = "Miss"
                        },
                        new
                        {
                            Id = 4,
                            SalutationName = "Dr"
                        },
                        new
                        {
                            Id = 5,
                            SalutationName = "Prof"
                        },
                        new
                        {
                            Id = 6,
                            SalutationName = "Rev"
                        },
                        new
                        {
                            Id = 7,
                            SalutationName = "Hon"
                        });
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'")
                        .IsFixedLength();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture");

                    b.Property<string>("SamProfileId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sam_profile_id");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("user_role");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("system_users", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Visa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateOnly>("ExpireDate")
                        .HasColumnType("date")
                        .HasColumnName("expire_date");

                    b.Property<DateOnly>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<string>("IssuedPlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("issued_place");

                    b.Property<int>("PassportId")
                        .HasColumnType("int")
                        .HasColumnName("passport_id");

                    b.Property<string>("VisaNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("visa_number");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CountryId" }, "fk_visas_countries");

                    b.HasIndex(new[] { "PassportId" }, "fk_visas_passports");

                    b.ToTable("visas", (string)null);
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.CustomerProfile", b =>
                {
                    b.HasOne("SkyVault.WebApi.Backend.Models.CustomerProfile", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_customerprofiles_customerprofiles");

                    b.HasOne("SkyVault.WebApi.Backend.Models.CommunicationMethod", "PreferredComm")
                        .WithMany("CustomerProfiles")
                        .HasForeignKey("PreferredCommId")
                        .IsRequired()
                        .HasConstraintName("fk_customerprofiles_communication_methods");

                    b.HasOne("SkyVault.WebApi.Backend.Models.Salutation", "Salutation")
                        .WithMany("CustomerProfiles")
                        .HasForeignKey("SalutationId")
                        .IsRequired()
                        .HasConstraintName("fk_customerprofiles_salutations");

                    b.HasOne("SkyVault.WebApi.Backend.Models.SystemUser", "SystemUser")
                        .WithMany("CustomerProfiles")
                        .HasForeignKey("SystemUserId")
                        .IsRequired()
                        .HasConstraintName("fk_customerprofiles_system_users");

                    b.Navigation("Parent");

                    b.Navigation("PreferredComm");

                    b.Navigation("Salutation");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.FrequentFlyerNumber", b =>
                {
                    b.HasOne("SkyVault.WebApi.Backend.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("FrequentFlyerNumbers")
                        .HasForeignKey("CustomerProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_frequentflyernumbers_customerprofiles");

                    b.Navigation("CustomerProfile");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Job", b =>
                {
                    b.HasOne("SkyVault.WebApi.Backend.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("Jobs")
                        .HasForeignKey("CustomerProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_jobs_customerprofiles");

                    b.HasOne("SkyVault.WebApi.Backend.Models.NotificationTemplate", "Template")
                        .WithMany("Jobs")
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("fk_jobs_notification_templates");

                    b.Navigation("CustomerProfile");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.NotificationTemplate", b =>
                {
                    b.HasOne("SkyVault.WebApi.Backend.Models.NotificationType", "NotificationTypeNavigation")
                        .WithMany("NotificationTemplates")
                        .HasForeignKey("NotificationType")
                        .IsRequired()
                        .HasConstraintName("fk_notification_templates_notification_types");

                    b.Navigation("NotificationTypeNavigation");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Passport", b =>
                {
                    b.HasOne("SkyVault.WebApi.Backend.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("Passports")
                        .HasForeignKey("CustomerProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_passports_customerprofiles");

                    b.HasOne("SkyVault.WebApi.Backend.Models.Nationality", "Nationality")
                        .WithMany("Passports")
                        .HasForeignKey("NationalityId")
                        .IsRequired()
                        .HasConstraintName("fk_passports_nationalities");

                    b.Navigation("CustomerProfile");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Visa", b =>
                {
                    b.HasOne("SkyVault.WebApi.Backend.Models.Country", "Country")
                        .WithMany("Visas")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("fk_visas_countries");

                    b.HasOne("SkyVault.WebApi.Backend.Models.Passport", "Passport")
                        .WithMany("Visas")
                        .HasForeignKey("PassportId")
                        .IsRequired()
                        .HasConstraintName("fk_visas_passports");

                    b.Navigation("Country");

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.CommunicationMethod", b =>
                {
                    b.Navigation("CustomerProfiles");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Country", b =>
                {
                    b.Navigation("Visas");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.CustomerProfile", b =>
                {
                    b.Navigation("FrequentFlyerNumbers");

                    b.Navigation("InverseParent");

                    b.Navigation("Jobs");

                    b.Navigation("Passports");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Nationality", b =>
                {
                    b.Navigation("Passports");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.NotificationTemplate", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.NotificationType", b =>
                {
                    b.Navigation("NotificationTemplates");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Passport", b =>
                {
                    b.Navigation("Visas");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.Salutation", b =>
                {
                    b.Navigation("CustomerProfiles");
                });

            modelBuilder.Entity("SkyVault.WebApi.Backend.Models.SystemUser", b =>
                {
                    b.Navigation("CustomerProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
